-- Qarz Daftari release 1 schema (PostgreSQL 16).
-- Part of docs/08-technical-spec/OUTPUT.md. Executed and checked on 2026-10-06; see the specification.
-- Conventions: uuid identifiers (version 7, generated by the application), timestamptz in UTC,
-- money as bigint whole UZS, every tenant table carries shop_id and is protected by row-level security.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------------------------------------------------------------------------
-- Platform-level tables (no tenant)
-- ---------------------------------------------------------------------------

CREATE TABLE app_user (
  id            uuid PRIMARY KEY,
  tg_id         bigint UNIQUE,                       -- erased on anonymization of a pure customer
  lang          text NOT NULL DEFAULT 'uz' CHECK (lang IN ('uz','ru')),
  active_shop   uuid,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE platform_setting (
  key           text PRIMARY KEY,                    -- trial_on, trial_days, price_uzs, sms_on, online_pay_on, card_number, review_group
  value         jsonb NOT NULL,
  updated_by    text NOT NULL,
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE admin_account (
  user_id       uuid PRIMARY KEY REFERENCES app_user(id),
  totp_secret   bytea NOT NULL,                      -- encrypted by the application
  status        text NOT NULL DEFAULT 'active' CHECK (status IN ('active','disabled'))
);

CREATE TABLE processed_update (update_id bigint PRIMARY KEY, at timestamptz NOT NULL DEFAULT now());

CREATE TABLE outbox_message (
  id            uuid PRIMARY KEY,
  channel       text NOT NULL CHECK (channel IN ('telegram','sms')),
  recipient     text NOT NULL,                       -- chat id or phone
  shop_id       uuid,                                -- for quota and tracing; not a tenant-scoped table
  payload       jsonb NOT NULL,
  dedupe_key    text UNIQUE,
  status        text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sent','failed')),
  attempts      smallint NOT NULL DEFAULT 0,
  next_try_at   timestamptz NOT NULL DEFAULT now(),
  created_at    timestamptz NOT NULL DEFAULT now(),
  sent_at       timestamptz
);
CREATE INDEX outbox_due ON outbox_message (next_try_at) WHERE status = 'pending';

-- ---------------------------------------------------------------------------
-- Tenant tables
-- ---------------------------------------------------------------------------

CREATE TABLE shop (
  id                    uuid PRIMARY KEY,
  name                  text NOT NULL CHECK (length(name) BETWEEN 1 AND 80),
  lang                  text NOT NULL DEFAULT 'uz' CHECK (lang IN ('uz','ru')),
  default_promise_days  smallint NOT NULL DEFAULT 30 CHECK (default_promise_days BETWEEN 1 AND 365),
  default_credit_limit  bigint CHECK (default_credit_limit > 0),
  sellers_may_exceed    boolean NOT NULL DEFAULT true,
  reminders_on          boolean NOT NULL DEFAULT false,
  reminder_tpl          smallint NOT NULL DEFAULT 1,
  reminder_hour         smallint NOT NULL DEFAULT 10 CHECK (reminder_hour BETWEEN 8 AND 20),
  sms_on                boolean NOT NULL DEFAULT false,
  status                text NOT NULL DEFAULT 'active' CHECK (status IN ('active','deletion_pending','erased')),
  deletion_due          timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE membership (
  id          uuid PRIMARY KEY,
  shop_id     uuid NOT NULL REFERENCES shop(id),
  user_id     uuid NOT NULL REFERENCES app_user(id),
  role        text NOT NULL CHECK (role IN ('owner','manager','seller')),
  status      text NOT NULL DEFAULT 'active' CHECK (status IN ('invited','active','suspended','removed')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (shop_id, user_id)
);
CREATE UNIQUE INDEX one_owner_per_shop ON membership (shop_id) WHERE role = 'owner' AND status = 'active';

CREATE TABLE invitation (
  token_hash  bytea PRIMARY KEY,                     -- SHA-256 of the token
  shop_id     uuid NOT NULL REFERENCES shop(id),
  kind        text NOT NULL CHECK (kind IN ('counter','customer','staff')),
  customer_id uuid,
  role        text CHECK (role IN ('manager','seller')),
  status      text NOT NULL DEFAULT 'issued' CHECK (status IN ('issued','used','cancelled','expired')),
  expires_at  timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CHECK ((kind = 'staff') = (role IS NOT NULL)),
  CHECK ((kind = 'customer') = (customer_id IS NOT NULL))
);

CREATE TABLE catalog_item (
  id          uuid PRIMARY KEY,
  shop_id     uuid NOT NULL REFERENCES shop(id),
  name        text NOT NULL CHECK (length(name) BETWEEN 1 AND 80),
  name_norm   text NOT NULL,
  unit        text NOT NULL DEFAULT 'dona',
  price       bigint NOT NULL CHECK (price > 0),
  learned     boolean NOT NULL DEFAULT false,
  status      text NOT NULL DEFAULT 'active' CHECK (status IN ('active','hidden')),
  UNIQUE (shop_id, name_norm)
);

CREATE TABLE customer (
  id            uuid PRIMARY KEY,
  shop_id       uuid NOT NULL REFERENCES shop(id),
  display_name  text NOT NULL CHECK (length(display_name) BETWEEN 1 AND 80),
  name_norm     text NOT NULL,
  phone         text,
  lang          text CHECK (lang IN ('uz','ru')),
  status        text NOT NULL DEFAULT 'active' CHECK (status IN ('active','archived','anonymized')),
  credit_limit  bigint CHECK (credit_limit > 0),
  reminders_off boolean NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX customer_name_trgm ON customer USING gin (name_norm gin_trgm_ops);
CREATE INDEX customer_shop ON customer (shop_id, status);

CREATE TABLE import_batch (
  id          uuid PRIMARY KEY,
  shop_id     uuid NOT NULL REFERENCES shop(id),
  status      text NOT NULL CHECK (status IN ('uploaded','validated','applied','undone','discarded')),
  file_id     uuid,
  summary     jsonb,
  author_id   uuid NOT NULL REFERENCES membership(id),
  created_at  timestamptz NOT NULL DEFAULT now(),
  applied_at  timestamptz
);

CREATE TABLE ledger_entry (
  id              uuid PRIMARY KEY,
  shop_id         uuid NOT NULL REFERENCES shop(id),
  customer_id     uuid NOT NULL REFERENCES customer(id),
  seq             integer NOT NULL,
  kind            text NOT NULL CHECK (kind IN ('credit','opening','payment','reversal')),
  amount          bigint NOT NULL CHECK (amount > 0),
  note            text CHECK (length(note) <= 200),
  reverses_id     uuid REFERENCES ledger_entry(id),
  author_id       uuid NOT NULL REFERENCES membership(id),
  import_batch_id uuid REFERENCES import_batch(id),
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (customer_id, seq),
  UNIQUE (reverses_id),                              -- an entry is reversed at most once
  CHECK ((kind = 'reversal') = (reverses_id IS NOT NULL))
);
CREATE INDEX ledger_shop_time ON ledger_entry (shop_id, created_at);

CREATE TABLE goods_line (
  id              uuid PRIMARY KEY,
  shop_id         uuid NOT NULL REFERENCES shop(id),
  entry_id        uuid NOT NULL REFERENCES ledger_entry(id),
  line_no         smallint NOT NULL CHECK (line_no > 0),
  catalog_item_id uuid REFERENCES catalog_item(id),
  name            text NOT NULL CHECK (length(name) BETWEEN 1 AND 80),
  qty             numeric(12,3) NOT NULL CHECK (qty > 0),
  unit            text NOT NULL,
  unit_price      bigint NOT NULL CHECK (unit_price > 0),
  line_total      bigint NOT NULL CHECK (line_total > 0),
  batch_at        timestamptz NOT NULL DEFAULT now(),  -- transaction start: one batch shares one value
  UNIQUE (entry_id, line_no)
);

CREATE TABLE promise (                                 -- latest row per entry is the current promised date
  id              uuid PRIMARY KEY,
  shop_id         uuid NOT NULL REFERENCES shop(id),
  entry_id        uuid NOT NULL REFERENCES ledger_entry(id),
  promised_date   date NOT NULL,
  reason          text,
  actor           text NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX promise_entry ON promise (entry_id, created_at DESC);

CREATE TABLE customer_link (
  id              uuid PRIMARY KEY,
  shop_id         uuid NOT NULL REFERENCES shop(id),
  customer_id     uuid REFERENCES customer(id),      -- null while waiting at the counter
  user_id         uuid REFERENCES app_user(id),      -- erased on anonymization
  status          text NOT NULL CHECK (status IN ('waiting','active','unreachable','ended')),
  consent_text_v  smallint,
  consent_at      timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  ended_at        timestamptz,
  CHECK (status = 'waiting' OR status = 'ended' OR (customer_id IS NOT NULL AND consent_at IS NOT NULL))
);
CREATE UNIQUE INDEX one_live_link_per_customer ON customer_link (customer_id) WHERE status IN ('active','unreachable');
CREATE UNIQUE INDEX one_link_per_user_per_shop ON customer_link (shop_id, user_id) WHERE status IN ('waiting','active','unreachable');

CREATE TABLE dispute (
  id              uuid PRIMARY KEY,
  shop_id         uuid NOT NULL REFERENCES shop(id),
  entry_id        uuid NOT NULL UNIQUE REFERENCES ledger_entry(id),   -- once per entry
  reason          text NOT NULL CHECK (length(reason) BETWEEN 3 AND 300),
  status          text NOT NULL DEFAULT 'open' CHECK (status IN ('open','reversed','declined','withdrawn')),
  decline_reason  text,
  decided_by      uuid REFERENCES membership(id),
  created_at      timestamptz NOT NULL DEFAULT now(),
  closed_at       timestamptz
);

CREATE TABLE payment_notice (
  id              uuid PRIMARY KEY,
  shop_id         uuid NOT NULL REFERENCES shop(id),
  customer_id     uuid NOT NULL REFERENCES customer(id),
  amount          bigint NOT NULL CHECK (amount > 0),
  file_id         uuid,
  status          text NOT NULL DEFAULT 'sent' CHECK (status IN ('sent','accepted','declined','expired')),
  payment_entry   uuid REFERENCES ledger_entry(id),
  decline_reason  text,
  decided_by      uuid REFERENCES membership(id),
  created_at      timestamptz NOT NULL DEFAULT now(),
  closed_at       timestamptz,
  CHECK ((status = 'accepted') = (payment_entry IS NOT NULL))
);

CREATE TABLE date_change_request (
  id              uuid PRIMARY KEY,
  shop_id         uuid NOT NULL REFERENCES shop(id),
  entry_id        uuid NOT NULL REFERENCES ledger_entry(id),
  requested_date  date NOT NULL,
  reason          text,
  status          text NOT NULL DEFAULT 'open' CHECK (status IN ('open','accepted','declined','expired')),
  decided_by      uuid REFERENCES membership(id),
  created_at      timestamptz NOT NULL DEFAULT now(),
  closed_at       timestamptz
);
CREATE UNIQUE INDEX one_open_date_request ON date_change_request (entry_id) WHERE status = 'open';

CREATE TABLE reminder (
  id          uuid PRIMARY KEY,
  shop_id     uuid NOT NULL REFERENCES shop(id),
  customer_id uuid NOT NULL REFERENCES customer(id),
  kind        text NOT NULL CHECK (kind IN ('auto','manual')),
  channel     text NOT NULL CHECK (channel IN ('telegram','sms')),
  amount      bigint NOT NULL CHECK (amount > 0),
  sent_on     date NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (customer_id, kind, sent_on)
);

CREATE TABLE removal_request (
  id          uuid PRIMARY KEY,
  shop_id     uuid NOT NULL REFERENCES shop(id),
  customer_id uuid NOT NULL REFERENCES customer(id),
  status      text NOT NULL CHECK (status IN ('waiting','completed')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE TABLE stored_file (
  id          uuid PRIMARY KEY,
  shop_id     uuid NOT NULL REFERENCES shop(id),
  purpose     text NOT NULL CHECK (purpose IN ('subscription_receipt','payment_notice','import')),
  object_key  text NOT NULL,
  sha256      bytea NOT NULL,
  size_bytes  integer NOT NULL CHECK (size_bytes > 0),
  mime        text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  delete_after timestamptz
);

CREATE TABLE subscription (
  shop_id       uuid PRIMARY KEY REFERENCES shop(id),
  state         text NOT NULL CHECK (state IN ('trial','active','limited','suspended')),
  trial_ends    date,
  paid_through  date,
  prior_state   text,
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE subscription_receipt (
  id            uuid PRIMARY KEY,
  shop_id       uuid NOT NULL REFERENCES shop(id),
  file_id       uuid REFERENCES stored_file(id),
  stated_amount bigint NOT NULL CHECK (stated_amount > 0),
  status        text NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted','approved','rejected')),
  months        smallint CHECK (months > 0),
  reject_reason text,
  decided_by    uuid REFERENCES app_user(id),
  created_at    timestamptz NOT NULL DEFAULT now(),
  decided_at    timestamptz,
  CHECK ((status = 'approved') = (months IS NOT NULL))
);

CREATE TABLE support_access (
  id          uuid PRIMARY KEY,
  shop_id     uuid NOT NULL REFERENCES shop(id),
  admin_id    uuid NOT NULL REFERENCES app_user(id),
  reason      text NOT NULL,
  starts_at   timestamptz NOT NULL DEFAULT now(),
  ends_at     timestamptz NOT NULL,
  CHECK (ends_at <= starts_at + interval '24 hours')
);

CREATE TABLE activity (                                -- insert-only
  id            uuid PRIMARY KEY,
  shop_id       uuid NOT NULL REFERENCES shop(id),
  at            timestamptz NOT NULL DEFAULT now(),
  actor_kind    text NOT NULL CHECK (actor_kind IN ('staff','customer','admin','system')),
  actor_id      uuid,
  action        text NOT NULL,
  subject_type  text NOT NULL,
  subject_id    uuid
);
CREATE INDEX activity_shop_time ON activity (shop_id, at DESC);

CREATE TABLE request_key (                             -- idempotency for API writes
  shop_id     uuid NOT NULL REFERENCES shop(id),
  key         text NOT NULL,
  response    jsonb NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (shop_id, key)
);

CREATE SCHEMA measure;                                 -- no names, phones, Telegram identities, or shop_id
CREATE TABLE measure.event (
  id          uuid PRIMARY KEY,
  at          timestamptz NOT NULL DEFAULT now(),
  shop_ref    uuid NOT NULL,                           -- opaque, not a foreign key
  entry_ref   uuid,
  kind        text NOT NULL,
  amount      bigint,
  promised    date,
  handle_ms   integer
);

-- ---------------------------------------------------------------------------
-- Goods lines: one batch per entry, in time, summing to the entry total
-- ---------------------------------------------------------------------------

CREATE FUNCTION goods_line_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  e ledger_entry%ROWTYPE;
BEGIN
  SELECT * INTO e FROM ledger_entry WHERE id = NEW.entry_id;
  IF e.kind <> 'credit' THEN
    RAISE EXCEPTION 'goods lines are allowed only on credit entries';
  END IF;
  IF EXISTS (SELECT 1 FROM goods_line g WHERE g.entry_id = NEW.entry_id AND g.batch_at <> NEW.batch_at) THEN
    RAISE EXCEPTION 'goods lines for this entry were already recorded';
  END IF;
  -- allowed until the end of the day after the sale, Tashkent time
  IF now() >= ((date_trunc('day', e.created_at AT TIME ZONE 'Asia/Tashkent') + interval '2 days') AT TIME ZONE 'Asia/Tashkent') THEN
    RAISE EXCEPTION 'the time for adding goods lines to this entry has passed';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER goods_line_guard BEFORE INSERT ON goods_line FOR EACH ROW EXECUTE FUNCTION goods_line_guard();

CREATE FUNCTION goods_line_sum_check() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  total bigint;
  expected bigint;
BEGIN
  SELECT sum(line_total) INTO total FROM goods_line WHERE entry_id = NEW.entry_id;
  SELECT amount INTO expected FROM ledger_entry WHERE id = NEW.entry_id;
  IF total <> expected THEN
    RAISE EXCEPTION 'goods lines sum to % but the entry total is %', total, expected;
  END IF;
  RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER goods_line_sum AFTER INSERT ON goods_line
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION goods_line_sum_check();

-- ---------------------------------------------------------------------------
-- Roles and row-level security
-- ---------------------------------------------------------------------------

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'qd_app') THEN
    CREATE ROLE qd_app NOLOGIN NOBYPASSRLS;  -- login and password are set at deploy
  END IF;
END $$;
GRANT USAGE ON SCHEMA public, measure TO qd_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO qd_app;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA measure TO qd_app;
-- insert-only tables
REVOKE UPDATE, DELETE, TRUNCATE ON ledger_entry, goods_line, promise, activity FROM qd_app;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'membership','invitation','catalog_item','customer','import_batch','ledger_entry','goods_line','promise',
    'customer_link','dispute','payment_notice','date_change_request','reminder','removal_request',
    'stored_file','subscription','subscription_receipt','support_access','activity','request_key'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'CREATE POLICY tenant ON %I USING (shop_id = nullif(current_setting(''qd.shop_id'', true), '''')::uuid) '
      'WITH CHECK (shop_id = nullif(current_setting(''qd.shop_id'', true), '''')::uuid)', t);
  END LOOP;
END $$;

ALTER TABLE shop ENABLE ROW LEVEL SECURITY;
ALTER TABLE shop FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant ON shop
  USING (id = nullif(current_setting('qd.shop_id', true), '')::uuid)
  WITH CHECK (id = nullif(current_setting('qd.shop_id', true), '')::uuid);

-- Cross-tenant reads (a user's own memberships and links, owner totals, platform administration, the
-- worker's reminder and expiry scans) go through SECURITY DEFINER functions owned by the migration role,
-- each taking the authenticated user or job identity as an argument. They are specified in the document.
