#!/usr/bin/env bash
# Start the rehearsal stack from nothing:
#   primary -> pgBackRest stanza and first full backup -> standby restored from that backup
#   and streaming -> file store with one bucket and one access key.
set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

if [ -n "$(docker ps -aq --filter label=com.docker.compose.project=qd-rehearsal)" ]; then
    die "the rehearsal stack already exists; run scripts/down.sh first"
fi

if [ ! -f "$ENV_FILE" ]; then
    log "generating throwaway secrets in deploy/rehearsal/$ENV_FILE (git-ignored)"
    (
        umask 077
        {
            echo "# Generated by scripts/up.sh for the local rehearsal. Throwaway values. Never commit."
            echo "QD_POSTGRES_PASSWORD=$(rand_hex 16)"
            echo "QD_REPL_PASSWORD=$(rand_hex 16)"
            echo "QD_BACKUP_CIPHER_PASS=$(rand_hex 32)"
            echo "QD_FILESTORE_RPC_SECRET=$(rand_hex 32)"
            echo "QD_FILESTORE_ADMIN_TOKEN=$(rand_hex 32)"
            echo "QD_FILESTORE_KEY_ID=GK$(rand_hex 12)"
            echo "QD_FILESTORE_KEY_SECRET=$(rand_hex 32)"
        } > "$ENV_FILE"
    )
    set -a
    # shellcheck disable=SC1090
    . "./$ENV_FILE"
    set +a
fi

t_start="$(now)"

log "building images"
dc build --quiet

log "starting the primary and the file store"
dc up -d pg-primary filestore
wait_healthy pg-primary 120

log "creating the pgBackRest stanza and checking that archiving works"
dc exec -T -u postgres pg-primary pgbackrest --stanza=qarz --log-level-console=warn stanza-create
dc exec -T -u postgres pg-primary pgbackrest --stanza=qarz --log-level-console=warn check

log "taking the first full base backup"
t_backup="$(now)"
dc exec -T -u postgres pg-primary pgbackrest --stanza=qarz --log-level-console=warn backup --type=full
log "full backup took $(seconds_between "$t_backup" "$(now)") s"

log "starting the standby (restored from the backup, then streaming)"
dc up -d pg-standby
wait_healthy pg-standby 180
wait_sql_true pg-primary \
    "select exists (select 1 from pg_stat_replication where application_name = 'pg-standby' and state = 'streaming' and sync_state = 'async')" \
    60 || die "the standby is not streaming from the primary"
[ "$(pg_sql pg-standby 'select pg_is_in_recovery()')" = "t" ] || die "the standby is not in recovery"

log "configuring the file store"
garage() { dc exec -T -e RUST_LOG=warn filestore /garage "$@"; }
waited=0
until garage status > /dev/null 2>&1; do
    [ "$waited" -lt 30 ] || die "the file store did not start"
    sleep 1
    waited=$((waited + 1))
done
node_id="$(garage node id -q | cut -d@ -f1)"
garage layout assign -z local -c 1G "$node_id" > /dev/null
garage layout apply --version 1 > /dev/null
garage key import --yes -n rehearsal "$QD_FILESTORE_KEY_ID" "$QD_FILESTORE_KEY_SECRET" > /dev/null
garage bucket create qd-files > /dev/null
garage bucket allow --read --write --owner qd-files --key rehearsal > /dev/null

log "rehearsal stack is up in $(seconds_between "$t_start" "$(now)") s"
cat <<EOF

  primary     127.0.0.1:${QD_PORT_PRIMARY:-55532}   (service pg-primary)
  standby     127.0.0.1:${QD_PORT_STANDBY:-55533}   (service pg-standby, read-only until promoted)
  file store  127.0.0.1:${QD_PORT_FILESTORE:-55900}   (S3 API, bucket qd-files)

Next: scripts/verify.sh   then   scripts/down.sh
EOF
