#!/usr/bin/env bash
# The proof on a developer machine: the production stack plus the local overlay (a throwaway PostgreSQL
# and a directory in place of the file store), a self-signed certificate, loopback ports.
#
#   local.sh up [<git-ref>]   generate the certificate and an env file, then run deploy.sh (default HEAD)
#   local.sh smoke            smoke.sh from outside, then a look at the proxy's access log
#   local.sh rollback <ref>   rollback.sh against the local stack
#   local.sh down             remove the containers, networks, volumes, the images and the generated files
#
# Everything generated lives in deploy/production/.local/ (ignored by git). The images are built from the
# COMMIT, not from the working tree: commit first.
# Environment: LOCAL_HTTP_PORT (18480), LOCAL_HTTPS_PORT (18443), DEPLOY_PROJECT (qd-deploy-proof).
set -euo pipefail

LOCAL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.local"
export DEPLOY_ENV_FILE="$LOCAL_DIR/local.env"
export DEPLOY_PROJECT="${DEPLOY_PROJECT:-qd-deploy-proof}"
export DEPLOY_STATE_DIR="$LOCAL_DIR/state"
export DEPLOY_COMPOSE_OVERLAY="$LOCAL_DIR/../compose.local.yml"
# shellcheck source=lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

HTTP_PORT="${LOCAL_HTTP_PORT:-18480}"
HTTPS_PORT="${LOCAL_HTTPS_PORT:-18443}"

generate() {
  mkdir -p "$LOCAL_DIR/tls" "$LOCAL_DIR/acme" "$DEPLOY_STATE_DIR"
  if [ ! -f "$LOCAL_DIR/tls/fullchain.pem" ]; then
    say "certificate: generating a self-signed one for localhost"
    MSYS_NO_PATHCONV=1 openssl req -x509 -newkey rsa:2048 -nodes -days 7 \
      -subj "/CN=localhost" -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" \
      -keyout "$(native_path "$LOCAL_DIR/tls/privkey.pem")" \
      -out "$(native_path "$LOCAL_DIR/tls/fullchain.pem")" 2>/dev/null
    chmod 644 "$LOCAL_DIR/tls/privkey.pem"  # read by user 101 in the container; a throwaway key
  fi
  if [ ! -f "$DEPLOY_ENV_FILE" ]; then
    say "env file: generating throwaway values"
    local owner app
    owner="$(openssl rand -hex 16)"; app="$(openssl rand -hex 16)"
    ( umask 077; cat > "$DEPLOY_ENV_FILE" <<EOF
# Generated by local.sh for the local proof. Throwaway values; nothing here exists outside this machine.
DEPLOY_TLS_DIR=$(native_path "$LOCAL_DIR/tls")
DEPLOY_ACME_DIR=$(native_path "$LOCAL_DIR/acme")
DEPLOY_BIND=127.0.0.1
DEPLOY_HTTP_PORT=$HTTP_PORT
DEPLOY_HTTPS_PORT=$HTTPS_PORT
VITE_BOT_USERNAME=qd_local_proof_bot
LOCAL_POSTGRES_PASSWORD=$owner
LOCAL_APP_PASSWORD=$app
QD_MIGRATION_URL=postgresql://postgres:$owner@db:5432/qarz
QD_DATABASE_URL=postgresql://qd_app:$app@db:5432/qarz
# Not a bot: a string of the right shape, so that the API serves its routes. Nothing is sent with it.
QD_BOT_TOKEN=1000000000:$(openssl rand -hex 18)
QD_WEBHOOK_SECRET=$(openssl rand -hex 24)
QD_SECRETS_KEY=$(openssl rand -base64 32)
QD_ADMIN_TG_IDS=1
QD_METRICS_TOKEN=$(openssl rand -hex 16)
QD_FILE_STORE=filesystem
QD_FILE_ROOT=/var/lib/qarz/files
EOF
    )
  fi
}

up() {
  RELEASE="$(resolve_commit "${1:-HEAD}")"
  generate
  ensure_images "$RELEASE"
  # What an operator does once on a real database host: the schema, then a password for qd_app.
  say "database: throwaway PostgreSQL, migrations, application role"
  compose up --detach --wait db
  compose run --rm migrate
  compose run --rm local-role
  bash "$SCRIPTS_DIR/deploy.sh" "$RELEASE"
}

smoke() {
  RELEASE="$(current_release)"
  [ -n "$RELEASE" ] || die "nothing is deployed: run local.sh up first"
  local marker status=0
  marker="smokemarker$(openssl rand -hex 6)"
  curl -sS -o /dev/null --insecure --max-time 10 "https://127.0.0.1:$HTTPS_PORT/healthz?secret=$marker" || true
  SMOKE_INSECURE=1 bash "$SCRIPTS_DIR/smoke.sh" "https://127.0.0.1:$HTTPS_PORT" "http://127.0.0.1:$HTTP_PORT" || status=$?

  echo "# from inside (not part of smoke.sh: needs the host)"
  local log metrics
  log="$(compose logs --no-log-prefix --no-color proxy 2>/dev/null)"
  inside() { if "${@:2}"; then printf 'ok    %s\n' "$1"; else printf 'FAIL  %s\n' "$1"; status=1; fi; }
  inside "the proxy's access log is JSON lines with a request id" \
    bash -c 'printf "%s\n" "$1" | grep -q "^{\"time\":.*\"request_id\":\"[0-9a-f]\{32\}\".*\"path\":\"/healthz\""' _ "$log"
  inside "the access log holds no query string" \
    bash -c '! printf "%s\n" "$1" | grep -q -e "$2" -e "?"' _ "$log" "$marker"
  inside "the API logged the proxy's request id" \
    bash -c 'id=$(printf "%s\n" "$1" | grep "\"path\":\"/api/v1/me\"" | tail -n 1 | sed "s/.*\"request_id\":\"\([0-9a-f]*\)\".*/\1/"); [ -n "$id" ] && printf "%s\n" "$2" | grep -q "$id"' \
    _ "$log" "$(compose logs --no-log-prefix --no-color api 2>/dev/null)"
  metrics="$(compose exec -T api python -c "import os,urllib.request as u; print(u.urlopen(u.Request('http://127.0.0.1:8000/metrics', headers={'Authorization': 'Bearer ' + os.environ['QD_METRICS_TOKEN']}), timeout=5).read().decode()[:4000])" 2>/dev/null || true)"
  inside "the metrics are served inside the network, with the token" \
    bash -c 'printf "%s" "$1" | grep -q qd_requests_total' _ "$metrics"
  inside "the API runs as a non-root user on a read-only file system" \
    bash -c '[ "$1" = "10001 ro" ]' _ "$(compose exec -T api sh -c 'printf "%s " "$(id -u)"; touch /app/x 2>/dev/null && echo rw || echo ro' 2>/dev/null | tr -d '\r')"
  inside "the proxy runs as a non-root user" \
    bash -c '[ "$1" = "101" ]' _ "$(compose exec -T proxy id -u 2>/dev/null | tr -d '\r')"
  inside "only the proxy publishes ports" \
    bash -c '[ "$1" = "proxy" ]' _ "$(docker ps --filter "label=com.docker.compose.project=$PROJECT" --format '{{.Label "com.docker.compose.service"}} {{.Ports}}' | grep -e '->' | awk '{print $1}' | sort -u | tr '
' ' ' | sed 's/ $//')"
  return "$status"
}

down() {
  RELEASE="$(current_release)"; RELEASE="${RELEASE:-none}"
  compose down --volumes --remove-orphans
  # Only the images this proof built: every tag of the two local image names.
  local images
  images="$(docker image ls --format '{{.Repository}}:{{.Tag}}' | grep -E '^qarz-daftari/(backend|proxy):' || true)"
  if [ -n "$images" ]; then
    # shellcheck disable=SC2086
    docker image rm $images >/dev/null
  fi
  rm -rf "$LOCAL_DIR"
  say "removed: project $PROJECT, its volumes and networks, the proof's images, $LOCAL_DIR"
}

case "${1:-}" in
  up) up "${2:-}" ;;
  smoke) smoke ;;
  rollback) bash "$SCRIPTS_DIR/rollback.sh" "${2:-}" ;;
  down) down ;;
  *) die "usage: local.sh up [<git-ref>] | smoke | rollback <git-ref> | down" ;;
esac
