#!/usr/bin/env bash
# The proof of the single-host deployment, on one machine, touching nothing outside it: the stack of
# compose.yml + compose.single-host.yml under its own Compose project, with compose.single-host.proof.yml
# putting a MinIO server in the place of Cloudflare R2 and a stand-in in the place of the tunnel. Nothing
# connects to Cloudflare or to Telegram; every way out of the stack is closed.
#
#   single-host-proof.sh up      generate an env file, build the images from HEAD (commit first), create
#                                the bucket, and bring the stack up with single-host.sh up
#   single-host-proof.sh run     the checks; prints PASS / FAIL lines, exit 0 only when none failed
#   single-host-proof.sh down    remove the containers, networks, volumes, images and generated files
#   single-host-proof.sh all     up, run, down (down also when run fails)
#
# Project `qd-single-proof`; no port is published. Everything generated is in
# deploy/production/.local-single/ (ignored by git). Commands for the containers are written in single
# quotes on purpose.
# shellcheck disable=SC2016
set -euo pipefail

PROOF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL_DIR="${LOCAL_DIR:-$PROOF_DIR/.local-single}"
export DEPLOY_ENV_FILE="$LOCAL_DIR/proof.env"
export DEPLOY_PROJECT="${DEPLOY_PROJECT:-qd-single-proof}"
export DEPLOY_STATE_DIR="$LOCAL_DIR/state"
export DEPLOY_COMPOSE_OVERLAY="$PROOF_DIR/compose.single-host.yml"
export DEPLOY_COMPOSE_OVERLAY_EXTRA="$PROOF_DIR/compose.single-host.proof.yml"
# shellcheck source-path=SCRIPTDIR source=lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

OUT_DIR="$LOCAL_DIR/out"
SINGLE="$SCRIPTS_DIR/single-host.sh"
VISITOR_A=203.0.113.9
VISITOR_B=203.0.113.10
FORGED=198.51.100.66
# A Python that runs (on Windows `python3` may be a stub that only prints where to buy one).
PYTHON=""
for candidate in python3 python; do
  if "$candidate" -c 'import json' > /dev/null 2>&1; then PYTHON="$candidate"; break; fi
done

case "$DEPLOY_PROJECT" in
  qd-single-*) ;;
  *) die "the proof runs only under a project named qd-single-*: it removes that project's volumes" ;;
esac

# docker compose for the proof. Arguments that look like paths belong to the containers, so Git Bash on
# Windows must not rewrite them.
dc() { MSYS_NO_PATHCONV=1 compose "$@"; }
single() { bash "$SINGLE" "$@"; }

load_state() {
  RELEASE="$(current_release)"
  [ -n "$RELEASE" ] || RELEASE="$(resolve_commit HEAD)"
  DEPLOY_PGBACKUP_TAG="$(cat "$DEPLOY_STATE_DIR/pgbackup-tag" 2>/dev/null || true)"
  [ -n "$DEPLOY_PGBACKUP_TAG" ] || DEPLOY_PGBACKUP_TAG="$(pgbackup_tag "$RELEASE")"
  export DEPLOY_PGBACKUP_TAG
}

# ------------------------------------------------------------------------------------------------- up
generate() {
  mkdir -p "$LOCAL_DIR" "$DEPLOY_STATE_DIR" "$OUT_DIR"
  [ ! -f "$DEPLOY_ENV_FILE" ] || return 0
  say "env file: generating throwaway values"
  ( umask 077; cat > "$DEPLOY_ENV_FILE" <<EOF
# Generated by single-host-proof.sh. Throwaway values; nothing here exists outside this machine.
DEPLOY_PUBLIC_HOST=qarz.proof.test
# Not a token: the proof runs no tunnel.
CLOUDFLARE_TUNNEL_TOKEN=proof-not-a-token
# The stand-in for R2 inside the Compose network.
DEPLOY_R2_ENDPOINT=r2
DEPLOY_R2_BUCKET=qd-proof
DEPLOY_R2_ACCESS_KEY_ID=proof$(openssl rand -hex 6)
DEPLOY_R2_SECRET_ACCESS_KEY=$(openssl rand -hex 20)
DEPLOY_BACKUP_PASSPHRASE=$(openssl rand -hex 32)
VITE_BOT_USERNAME=qd_local_proof_bot
QD_MIGRATION_URL=postgresql://postgres:$(openssl rand -hex 24)@db:5432/qarz
QD_DATABASE_URL=postgresql://qd_app:$(openssl rand -hex 24)@db:5432/qarz
QD_ADMIN_DATABASE_URL=postgresql://qd_admin:$(openssl rand -hex 24)@db:5432/qarz
QD_WORKER_DATABASE_URL=postgresql://qd_worker:$(openssl rand -hex 24)@db:5432/qarz
# Not a bot: a string of the right shape, so that the API serves its routes. Nothing is sent with it.
QD_BOT_TOKEN=1000000000:$(openssl rand -hex 18)
QD_WEBHOOK_SECRET=$(openssl rand -hex 24)
QD_SECRETS_KEY=$(openssl rand -base64 32)
QD_ADMIN_TG_IDS=1
QD_METRICS_TOKEN=$(openssl rand -hex 16)
EOF
  )
}

up() {
  generate
  RELEASE="$(resolve_commit HEAD)"
  load_state
  say "building what is missing, then the stand-in for R2 and its bucket"
  # single-host.sh would build the images itself; the bucket has to exist before it looks at it, and
  # the bucket is made with the database image.
  ensure_images "$RELEASE"
  ensure_pgbackup_image "$RELEASE"
  dc up --detach --wait --wait-timeout 120 r2
  # A key limited to its bucket cannot create one (env.sh tells rclone not to try); here the key is the
  # stand-in's own administrator, and the proof says so for this one command.
  dc run --rm --no-deps backup bash -c '. /opt/qarz-single/env.sh; qd_rclone_env; RCLONE_CONFIG_QDR2_NO_CHECK_BUCKET=false rc mkdir "qdr2:$QD_R2_BUCKET"'
  single up "$RELEASE"
}

# ----------------------------------------------------------------------------------------------- down
down() {
  load_state
  dc --profile restore --profile scratch down --volumes --remove-orphans || true
  # Only the images this proof built: the release's two and the database image of its tag.
  local image
  for image in "$(backend_image "$RELEASE")" "$(proxy_image "$RELEASE")" "$(pgbackup_image)"; do
    docker image rm "$image" >/dev/null 2>&1 || true
  done
  rm -rf "$LOCAL_DIR"
  say "removed: project $PROJECT with its volumes and networks, the proof's images, $LOCAL_DIR"
}

# ------------------------------------------------------------------------------------------------ run
passes=0
failures=0
pass() { passes=$((passes + 1)); echo "PASS  $*"; }
fail() { failures=$((failures + 1)); echo "FAIL  $*"; }
section() { printf '\n== %s\n' "$*"; }
# expect <description> <command...>: passes when the command succeeds
expect() {
  local description="$1"; shift
  if "$@"; then pass "$description"; else fail "$description"; fi
}
refuses() { ! "$@" > /dev/null 2>&1; }
# volume_is_empty VOLUME: true when the volume holds nothing (or does not exist: Docker makes it, empty)
volume_is_empty() {
  [ -z "$(docker_in run --rm --network none -v "$1:/v" --entrypoint sh "$(pgbackup_image)" -c 'ls -A /v' 2>/dev/null)" ]
}

last_out=""
last_code=0
# step NAME EXPECTED_EXIT COMMAND...: runs it, shows its standard output and the telling lines of its
# standard error, and judges the exit code. EXPECTED_EXIT is a number or "nonzero".
step() {
  local name="$1" want="$2" ok=0
  shift 2
  last_code=0
  "$@" > "$OUT_DIR/$name.out" 2> "$OUT_DIR/$name.err" || last_code=$?
  last_out="$(cat "$OUT_DIR/$name.out")"
  grep -E '^\{|^(PASS|FAIL|ok|skip|smoke)' "$OUT_DIR/$name.out" | tail -n 4 | sed 's/^/      /' || true
  grep -E '^(FAILED|ERROR|REFUSED|rows in)' "$OUT_DIR/$name.err" | tail -n 6 | sed 's/^/      /' || true
  if [ "$want" = nonzero ]; then
    [ "$last_code" != 0 ] && ok=1
  else
    [ "$last_code" = "$want" ] && ok=1
  fi
  if [ "$ok" = 1 ]; then
    pass "$name: exit $last_code (expected $want)"
  else
    fail "$name: exit $last_code, expected $want"
    tail -n 15 "$OUT_DIR/$name.err" | sed 's/^/      | /'
    tail -n 8 "$OUT_DIR/$name.out" | sed 's/^/      | /'
  fi
}
# field NAME: that field of the last JSON line the last step printed
field() { sed -n "s/.*\"$1\":\"\{0,1\}\([^\",}]*\).*/\1/p" <<< "$last_out" | tail -n 1; }
expect_field() {
  local got
  got="$(field "$1")"
  if [ "$got" = "$2" ]; then pass "$1 is $2"; else fail "$1 is '$got', expected '$2'"; fi
}
said() { grep -qF -- "$2" "$OUT_DIR/$1.err" "$OUT_DIR/$1.out"; }

sql() { dc exec -T db psql -X -qAt -v ON_ERROR_STOP=1 -U postgres -d qarz -c "$1" | tr -d '\r'; }
job() { dc exec -T backup /opt/qarz-single/job.sh "$@"; }
in_tunnel() { dc exec -T cloudflared "$@"; }
# docker, with arguments that are paths inside a container.
docker_in() { MSYS_NO_PATHCONV=1 docker "$@"; }
proxy_log() { dc logs --no-log-prefix --no-color proxy 2>/dev/null; }
# What the bucket holds, as it is: names and bytes, without the passphrase.
bucket() { dc exec -T backup bash -c '. /opt/qarz-single/env.sh; qd_rclone_env; '"$1"; }

# Close the current WAL segment and wait until the bucket has it.
archive_now() {
  local segment waited=0
  segment="$(sql "select pg_walfile_name(pg_current_wal_lsn())")"
  sql "select pg_logical_emit_message(true, 'proof', ''); select pg_switch_wal()" > /dev/null
  until [ "$(sql "select coalesce(last_archived_wal, '') >= '$segment' from pg_stat_archiver")" = t ]; do
    [ "$waited" -lt 120 ] || return 1
    sleep 2; waited=$((waited + 2))
  done
}

wait_for() { # wait_for SECONDS COMMAND...
  local limit="$1" waited=0
  shift
  until "$@" > /dev/null 2>&1; do
    [ "$waited" -lt "$limit" ] || return 1
    sleep 3; waited=$((waited + 3))
  done
}

fingerprint() { # what must be the same after a restore
  sql "select (select version_num from alembic_version) || ' markers ' || (select count(*) || ':' || coalesce(md5(string_agg(label, ',' order by id)), '') from qd_proof_marker) || ' entries ' || (select count(*) || ':' || coalesce(sum(amount), 0) from ledger_entry) || ' debts ' || (select count(*) from open_debt)"
}

run() {
  load_state
  mkdir -p "$OUT_DIR"
  [ -n "$(dc ps --quiet proxy 2>/dev/null)" ] || die "the proof stack is not up; run: single-host-proof.sh up"
  local started peer real_config
  started="$(date +%s)"
  # The address the stand-in's requests reach the proxy from (the stand-in is on two networks).
  peer="$(in_tunnel curl -sS -o /dev/null -w '%{local_ip}' http://proxy:8080/nginx-health | tr -d '\r ')"

  # ---------------------------------------------------------------------------------------------
  section "1. The composition as it will run for real (no proof overlay), checked without starting anything"
  real_config="$OUT_DIR/real-config.json"
  if DEPLOY_COMPOSE_OVERLAY_EXTRA="" dc --profile restore --profile scratch config --format json > "$real_config" 2> "$OUT_DIR/real-config.err"; then
    pass "compose.yml + compose.single-host.yml is a valid composition"
  else
    fail "compose.yml + compose.single-host.yml is not valid"
  fi
  if [ -n "$PYTHON" ]; then
    "$PYTHON" "$SCRIPTS_DIR/single_host_static.py" < "$real_config" || failures=$((failures + 1))
    "$PYTHON" "$SCRIPTS_DIR/single_host_static.py" --self-test < "$real_config" || failures=$((failures + 1))
  else
    fail "no python on this machine: the static checks did not run"
  fi
  # Without a token there is no composition at all: the tunnel cannot be started by mistake without one.
  grep -v '^CLOUDFLARE_TUNNEL_TOKEN=' "$DEPLOY_ENV_FILE" > "$LOCAL_DIR/no-token.env"
  step config-without-token nonzero env DEPLOY_ENV_FILE="$LOCAL_DIR/no-token.env" DEPLOY_COMPOSE_OVERLAY_EXTRA="" \
    DEPLOY_PGBACKUP_TAG="$DEPLOY_PGBACKUP_TAG" RELEASE="$RELEASE" bash -c '. "$0/lib.sh"; compose config --quiet' "$SCRIPTS_DIR"
  expect "the refusal names the missing setting" said config-without-token "CLOUDFLARE_TUNNEL_TOKEN is not set"
  rm -f "$LOCAL_DIR/no-token.env"
  # The pinned tunnel image, run with no network at all: it is the program the composition expects.
  local tunnel_image
  tunnel_image="$(sed -n 's/^ *image: \(cloudflare\/cloudflared:.*\)$/\1/p' "$PROOF_DIR/compose.single-host.yml")"
  step tunnel-image-version 0 docker run --rm --network none "$tunnel_image" --version
  step tunnel-image-commands 0 docker run --rm --network none "$tunnel_image" tunnel --help
  expect "the pinned image has the commands the composition uses (run, ready)" \
    bash -c 'grep -qE "^ +run " "$1" && grep -qE "^ +ready " "$1" && grep -q -- "--no-autoupdate" "$1"' _ "$OUT_DIR/tunnel-image-commands.out"
  expect "no container of the running stack publishes a port" \
    bash -c '[ -z "$(docker ps --filter "label=com.docker.compose.project=$1" --format "{{.Ports}}" | grep -e "->" || true)" ]' _ "$PROJECT"
  expect "the stand-in for the tunnel holds no token" \
    bash -c '[ "$1" = 0 ]' _ "$(dc exec -T cloudflared bash -c 'env | grep -c TUNNEL || true' | tr -d '\r')"

  # ---------------------------------------------------------------------------------------------
  section "2. The proxy as the tunnel reaches it (smoke.sh from the tunnel's place, visitor $VISITOR_A)"
  step smoke 0 dc exec -T -e SMOKE_VIA_TUNNEL="$VISITOR_A" -e SMOKE_AUTH_WAIT=0 cloudflared \
    bash -s -- http://proxy:8080 http://proxy:8080 < "$SCRIPTS_DIR/smoke.sh"
  expect "smoke.sh ran its checks ($(grep -c '^ok ' "$OUT_DIR/smoke.out" || true) ok, $(grep -c '^FAIL' "$OUT_DIR/smoke.out" || true) failed)" \
    bash -c '[ "$(grep -c "^ok " "$1")" -ge 90 ]' _ "$OUT_DIR/smoke.out"
  grep '^FAIL' "$OUT_DIR/smoke.out" | sed 's/^/      /' || true

  section "3. The visitor's address: taken from Cloudflare's header when the tunnel says it"
  local marker log line
  marker="proofmarker$(openssl rand -hex 6)"
  in_tunnel curl -sS -o /dev/null -H "X-Forwarded-Proto: https" -H "CF-Connecting-IP: $VISITOR_A" "http://proxy:8080/api/v1/$marker?secret=$marker" || true
  log="$(proxy_log)"
  line="$(grep "/api/v1/$marker" <<< "$log" | tail -n 1)"
  echo "      $line"
  expect "the access log has the visitor's address, not the tunnel's" grep -q "\"remote_addr\":\"$VISITOR_A\"" <<< "$line"
  expect "and the peer it came from is the tunnel's container ($peer)" grep -q "\"peer\":\"$peer\"" <<< "$line"
  expect "the access log still holds no query string" bash -c '! grep -q -e "secret=" -e "?" <<< "$1"' _ "$log"
  # smoke.sh has just used up visitor A's sign-in allowance. Limits by address mean: A is refused, B is not.
  # The allowance refills by one every two seconds, so A is asked several times at once.
  local status_a status_b
  sign_in_as() {
    in_tunnel curl -sS -o /dev/null -w '%{http_code} ' -X POST -H 'Content-Type: application/json' --data '{}' \
      -H "X-Forwarded-Proto: https" -H "CF-Connecting-IP: $1" http://proxy:8080/api/v1/auth/telegram-webapp || true
  }
  status_a="$(for _ in 1 2 3 4 5 6 7 8 9 10 11 12 13 14; do sign_in_as "$VISITOR_A"; done)"
  status_b="$(sign_in_as "$VISITOR_B")"
  expect "the sign-in limit counts by visitor: $VISITOR_A is refused (got $status_a)" grep -q 429 <<< "$status_a"
  expect "and another visitor through the same tunnel is not (got $status_b)" \
    bash -c 'case "$1" in "429 " | "000 " | "") exit 1 ;; *) exit 0 ;; esac' _ "$status_b"
  # What the API is told about the visitor's scheme: its own redirects must point at https.
  local location
  location="$(in_tunnel curl -sS -o /dev/null -D - -H "X-Forwarded-Proto: https" -H "CF-Connecting-IP: $VISITOR_B" -H "Host: qarz.proof.test" http://proxy:8080/api/v1/me/ | tr -d '\r' | sed -n 's/^[Ll]ocation: *//p')"
  if [ -n "$location" ]; then
    expect "a redirect made by the API names https and the public host ($location)" bash -c 'case "$1" in https://qarz.proof.test/*) exit 0 ;; *) exit 1 ;; esac' _ "$location"
  else
    echo "      the API answers /api/v1/me/ without a redirect: nothing to check"
  fi

  section "4. Negative: the same headers from anyone who is not the tunnel are not believed"
  marker="forgedmarker$(openssl rand -hex 6)"
  # The API's container shares a network with the proxy (the proxy calls it); it is not the tunnel.
  local forged_status api_address logged_address logged_peer
  api_address="$(dc exec -T api python -c 'import socket; s = socket.create_connection(("proxy", 8080), timeout=5); print(s.getsockname()[0])' | tr -d '\r ')"
  forged_status="$(dc exec -T api python -c '
import http.client, sys
c = http.client.HTTPConnection("proxy", 8080, timeout=10)
c.request("GET", "/api/v1/" + sys.argv[1], headers={"CF-Connecting-IP": sys.argv[2], "X-Forwarded-Proto": "https", "X-Forwarded-For": sys.argv[2], "X-Real-IP": sys.argv[2]})
r = c.getresponse(); print(r.status, r.getheader("Location") or "")' "$marker" "$FORGED" | tr -d '\r')"
  line="$(proxy_log | grep "/api/v1/$marker" | tail -n 1)"
  echo "      answer: $forged_status"
  echo "      $line"
  expect "its claim to be an HTTPS visitor is not believed: it is redirected, not served" \
    bash -c 'case "$1" in "301 https://"*) exit 0 ;; *) exit 1 ;; esac' _ "$forged_status"
  expect "the forged address $FORGED is not in the access log" bash -c '! grep -q "$2" <<< "$1"' _ "$line" "$FORGED"
  logged_address="$(sed -n 's/.*"remote_addr":"\([0-9.]*\)".*/\1/p' <<< "$line")"
  logged_peer="$(sed -n 's/.*"peer":"\([0-9.]*\)".*/\1/p' <<< "$line")"
  expect "the access log has the caller's real address ($api_address) as both the address and the peer" \
    bash -c '[ -n "$1" ] && [ "$1" = "$2" ] && [ "$1" = "$3" ]' _ "$api_address" "$logged_address" "$logged_peer"
  expect "the proxy refuses to start when told to believe a whole network" \
    refuses docker_in run --rm --network none -e QD_TUNNEL_PEER=10.99.240.0/28 \
    --entrypoint /usr/local/bin/qd-single-host-proxy "$(proxy_image "$RELEASE")"

  # ---------------------------------------------------------------------------------------------
  section "5. The schedule: its own first run, and its calendar"
  expect "without being asked, the scheduler took a full backup, ran the restore test, expired and wrote the monthly dump" \
    wait_for 240 dc exec -T backup bash -c 'for j in full restore-test expire monthly; do [ -s "/var/lib/qarz-backup/scheduler/$j.done" ] || exit 1; done'
  dc logs --no-log-prefix --no-color backup 2>/dev/null | grep '"event":"scheduler_job"' | sed 's/^/      /' | tail -n 8 || true
  local slots
  slots="$(dc exec -T backup bash -c '/opt/qarz-single/scheduler.sh slots "$(date -d "2026-10-08 12:00" +%s)" | cut -d" " -f1,3-; echo --; /opt/qarz-single/scheduler.sh slots "$(date -d "2026-10-04 01:29" +%s)" | cut -d" " -f1,3-; echo --; /opt/qarz-single/scheduler.sh slots "$(date -d "2026-10-01 04:29" +%s)" | grep monthly | cut -d" " -f1,3-' | tr -d '\r')"
  while IFS= read -r line; do echo "      $line"; done <<< "$slots"
  expect "Thursday 8 October at noon: full of Sunday, differential of today, restore test of Wednesday, monthly of the 1st" \
    bash -c '[ "$(sed -n "1,5p" <<< "$1" | tr "\n" "|")" = "full Sun 2026-10-04 01:30 +05|diff Thu 2026-10-08 01:30 +05|restore-test Wed 2026-10-07 02:30 +05|expire Thu 2026-10-08 03:30 +05|monthly Thu 2026-10-01 04:30 +05|" ]' _ "$slots"
  expect "Sunday at 01:29 the full backup due is still last Sunday's (a moment in the future is never due)" \
    bash -c 'sed -n "7,8p" <<< "$1" | tr "\n" "|" | grep -qx "full Sun 2026-09-27 01:30 +05|diff Sat 2026-10-03 01:30 +05|"' _ "$slots"
  expect "on the 1st at 04:29 the monthly dump due is last month's" grep -qx "monthly Tue 2026-09-01 04:30 +05" <<< "$slots"

  # ---------------------------------------------------------------------------------------------
  section "6. Data to protect: a shop with a debt, built by the real migrations"
  sql "create table if not exists qd_proof_marker (id bigserial primary key, label text not null, at timestamptz not null default clock_timestamp())"
  sql "
    insert into app_user (id, tg_id) values ('00000000-0000-4000-8000-0000000000a1', 9900000001);
    insert into shop (id, name) values ('00000000-0000-4000-8000-0000000000b1', 'Proof shop');
    insert into membership (id, shop_id, user_id, role) values ('00000000-0000-4000-8000-0000000000c1', '00000000-0000-4000-8000-0000000000b1', '00000000-0000-4000-8000-0000000000a1', 'owner');
    insert into customer (id, shop_id, display_name, name_norm) values ('00000000-0000-4000-8000-0000000000d1', '00000000-0000-4000-8000-0000000000b1', 'Proof customer', 'proof customer');
    insert into ledger_entry (id, shop_id, customer_id, seq, kind, amount, author_id) values ('00000000-0000-4000-8000-0000000000e1', '00000000-0000-4000-8000-0000000000b1', '00000000-0000-4000-8000-0000000000d1', 1, 'credit', 50000, '00000000-0000-4000-8000-0000000000c1');
    insert into promise (id, shop_id, entry_id, promised_date, actor) values (gen_random_uuid(), '00000000-0000-4000-8000-0000000000b1', '00000000-0000-4000-8000-0000000000e1', current_date + 7, 'default');
    insert into qd_proof_marker (label) select 'before-backup-' || g from generate_series(1, 500) g" > /dev/null
  expect "the ledger has one open debt and the stored open debts agree with it" \
    [ "$(sql "select concat_ws(' ', (select count(*) from open_debt), (select count(*) from open_debt_mismatches(NULL)))")" = "1 0" ]

  section "7. A differential backup by command, the check, the figures"
  step backup-diff 0 single backup diff
  expect_field taken_type diff
  archive_now || fail "the WAL segment did not reach the bucket"
  step check-fresh 0 job check
  expect "the repository in the bucket is encrypted (pgBackRest says aes-256-cbc)" \
    [ "$(bucket 'pgbackrest info --output=json | jq -r ".[0].cipher"' | tr -d '\r')" = aes-256-cbc ]
  # An unencrypted repository keeps its own records as plain text (backrest-format, db-system-id), even
  # though the data files in it are compressed and show nothing: those two words are what gives it away.
  expect "nothing readable is in the bucket's objects: none of pgBackRest's own records, no table name" \
    bucket 'd="$(mktemp -d)"; rc copy "qdr2:$QD_R2_BUCKET/pgbackrest" "$d" --max-size 3M --transfers 8 2>/dev/null; n="$(find "$d" -type f | wc -l)"; [ "$n" -gt 5 ] && ! grep -rlqa -e "backrest-format" -e "db-system-id" -e "ledger_entry" -e "qd_proof_marker" "$d"; code=$?; rm -rf "$d"; exit $code'
  # Negative: nothing is recent enough (the thresholds shortened to one second for this one run).
  sleep 2
  step check-backup-too-old 1 dc exec -T -e QD_MAX_BACKUP_AGE_SECONDS=1 -e QD_MAX_FULL_AGE_SECONDS=1 backup /opt/qarz-single/job.sh check
  step health-after-stale-check 1 dc exec -T backup /opt/qarz-single/healthcheck.sh
  step check-fresh-again 0 job check
  step health-after-fresh-check 0 dc exec -T backup /opt/qarz-single/healthcheck.sh
  local figures wanted
  figures="$(dc exec -T backup bash -c 'cat /var/lib/qarz-backup/textfile/*.prom' | grep -v '^#' | tr -d '\r')"
  echo "$figures" | sort | sed 's/^/      /'
  for wanted in 'qd_backup_last_success_timestamp_seconds{type="full"}' 'qd_backup_last_success_timestamp_seconds{type="diff"}' \
    'qd_backup_restore_test_last_success_timestamp_seconds' 'qd_backup_last_run_success{type="diff"}'; do
    expect "written and not zero: $wanted" bash -c 'grep -F "$2 " <<< "$1" | grep -qv " 0$"' _ "$figures" "$wanted"
  done

  # ---------------------------------------------------------------------------------------------
  section "8. The stored files: an encrypted copy in the bucket"
  dc exec -T api python -c '
import os, pathlib
root = pathlib.Path("/var/lib/qarz/files")
for name, size in (("receipts/2026/a-receipt.jpg", 30000), ("receipts/2026/b-receipt.jpg", 5000), ("imports/c-import.csv", 0)):
    path = root / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(b"QDPROOFPLAINTEXT name,amount\n" + os.urandom(size))
    os.chmod(path, 0o600)'
  local files_before
  files_before="$(dc exec -T api sh -c 'cd /var/lib/qarz/files && find . -type f | sort | xargs sha256sum' | tr -d '\r')"
  # What the bucket holds under crypt/ before the files go there: the monthly dump, if it was written.
  local objects_before objects_after
  objects_before="$(bucket 'rc lsf -R --files-only "qdr2:$QD_R2_BUCKET/crypt" 2>/dev/null | wc -l' | tr -d '\r ')"
  step files-sync 0 dc exec -T files-backup /opt/qarz-single/files-sync.sh sync
  expect_field objects_count 3
  step files-health-after-a-copy 0 dc exec -T files-backup /opt/qarz-single/files-health.sh
  # Negative: the same copy is too old when the allowance is nothing (3 x -40 + 120 seconds = 0).
  sleep 3
  step files-health-when-the-copy-is-old 1 dc exec -T -e QD_FILES_INTERVAL=-40 files-backup /opt/qarz-single/files-health.sh
  objects_after="$(bucket 'rc lsf -R --files-only "qdr2:$QD_R2_BUCKET/crypt" | wc -l' | tr -d '\r ')"
  expect "the bucket holds three more objects ($objects_before before, $objects_after after)" [ "$((objects_after - objects_before))" = 3 ]
  expect "no object in the bucket has a name of theirs, or says what it is" \
    bucket 'names="$(rc lsf -R "qdr2:$QD_R2_BUCKET/crypt")"; [ -n "$names" ] && ! grep -q -i -e receipt -e import -e jpg -e csv -e current -e removed -e monthly -e dump <<< "$names"'
  expect "and none has their content: the marker written into every file is not in the bucket" \
    bucket 'd="$(mktemp -d)"; rc copy "qdr2:$QD_R2_BUCKET/crypt" "$d" 2>/dev/null; [ "$(find "$d" -type f | wc -l)" -ge 3 ] && ! grep -rlqa -e QDPROOFPLAINTEXT -e PGDMP "$d"; code=$?; rm -rf "$d"; exit $code'
  dc exec -T api sh -c 'rm /var/lib/qarz/files/receipts/2026/a-receipt.jpg /var/lib/qarz/files/receipts/2026/b-receipt.jpg'
  step files-sync-mass-delete nonzero dc exec -T -e QD_FILES_MAX_DELETE=1 files-backup /opt/qarz-single/files-sync.sh sync
  expect "a run that would remove more files than allowed stopped (QD_FILES_MAX_DELETE=1 here; 100 by default) and the copy still holds two" \
    [ "$(bucket 'rc size --json qdcrypt:current | jq .count' | tr -d '\r')" -ge 2 ]
  dc exec -T api sh -c 'rm -rf /var/lib/qarz/files/imports /var/lib/qarz/files/receipts'
  step files-sync-empty-source nonzero dc exec -T files-backup /opt/qarz-single/files-sync.sh sync
  expect "an emptied directory was not synchronised over the copy" said files-sync-empty-source "nothing was changed"
  step files-restore 0 dc run --rm --no-deps restore-files
  step files-sync-after-restore 0 dc exec -T files-backup /opt/qarz-single/files-sync.sh sync
  local files_after
  files_after="$(dc exec -T api sh -c 'cd /var/lib/qarz/files && find . -type f | sort | xargs sha256sum' | tr -d '\r')"
  # One of the three was moved aside by the refused run before it stopped; it is in removed/, not lost.
  expect "the files restored from the bucket are byte for byte the ones that were copied ($(wc -l <<< "$files_after") of 3 in current/)" \
    bash -c '[ -n "$2" ] && [ -z "$(comm -13 <(echo "$1") <(echo "$2"))" ]' _ "$files_before" "$files_after"
  expect "what the refused run had already moved aside is kept in removed/ for 30 days" \
    [ "$(( $(bucket 'rc size --json qdcrypt:current | jq .count' | tr -d '\r') + $(bucket 'rc size --json qdcrypt:removed | jq .count' | tr -d '\r') ))" -ge 3 ]

  # ---------------------------------------------------------------------------------------------
  section "9. The restore test: passes on a good backup, and leaves the live database alone"
  local born
  born="$(sql 'select pg_postmaster_start_time()')"
  step restore-test 0 single restore-test
  expect_field outcome ok
  expect_field backup_type diff
  echo "MEASURE restore_seconds $(field restore_seconds), start_seconds $(field start_seconds), whole test $(field duration_seconds) s"
  expect "the live database was not restarted or touched by it" [ "$(sql 'select pg_postmaster_start_time()')" = "$born" ]
  expect "the throwaway instance was removed" bash -c '[ -z "$1" ]' _ "$(dc exec -T backup bash -c 'ls -d /var/lib/qarz-backup/scratch/qd-restore-test.* 2>/dev/null || true' | tr -d '\r')"

  section "10. Negative: the restore test fails when the restored data is damaged"
  # (a) the ledger: a stored open debt that the entries do not explain.
  sql "delete from open_debt" > /dev/null
  step backup-diff-damaged-ledger 0 job diff
  step restore-test-damaged-ledger 1 job restore-test
  expect_field failed_check ledger
  expect "it was the comparison of the open debts with the ledger that refused" said restore-test-damaged-ledger "differ from the ledger"
  sql "select refresh_open_debts(array['00000000-0000-4000-8000-0000000000d1'::uuid])" > /dev/null
  expect "the damage was repaired in the source" [ "$(sql 'select count(*) from open_debt_mismatches(NULL)')" = 0 ]
  step backup-diff-repaired 0 job diff
  step restore-test-repaired 0 job restore-test
  # (b) the backup itself: its largest object in the bucket overwritten with random bytes.
  local label object
  label="$(field backup)"
  object="$(bucket 'rc lsf -R --files-only --format sp "qdr2:$QD_R2_BUCKET/pgbackrest/backup/qarz/'"$label"'" | grep -v backup.manifest | sort -n | tail -n 1 | sed "s/^ *[0-9]*;//"' | tr -d '\r')"
  bucket 'size="$(rc size --json "qdr2:$QD_R2_BUCKET/pgbackrest/backup/qarz/'"$label/$object"'" | jq .bytes)"; head -c "$size" /dev/urandom | rc rcat "qdr2:$QD_R2_BUCKET/pgbackrest/backup/qarz/'"$label/$object"'"'
  echo "      overwrote with random bytes: backup/qarz/$label/$object"
  step restore-test-damaged-backup 1 job restore-test
  expect_field failed_check restore
  step backup-full-after-damage 0 job full
  step restore-test-after-new-backup 0 job restore-test

  section "11. Negative: with another passphrase the bucket is worthless"
  step read-with-wrong-passphrase nonzero dc run --rm --no-deps -e QD_BACKUP_PASSPHRASE=not-the-passphrase backup bash -c 'pgbackrest --stanza=qarz --log-level-console=warn info --output=json | jq -e ".[0].backup | length > 0"'
  step files-with-wrong-passphrase nonzero dc run --rm --no-deps -e QD_BACKUP_PASSPHRASE=not-the-passphrase restore-files

  # ---------------------------------------------------------------------------------------------
  section "12. The monthly dump and expiry"
  step monthly 0 job monthly
  expect "the bucket holds this month's dump" [ "$(bucket 'rc lsf qdcrypt:monthly | grep -c "^db-$(date +%Y%m).dump.enc$"' | tr -d '\r')" = 1 ]
  step expire 0 job expire

  # ---------------------------------------------------------------------------------------------
  section "13. A point-in-time copy beside the live database (runbook 3)"
  local moment
  sql "insert into qd_proof_marker (label) values ('before-the-moment')" > /dev/null
  sleep 2
  moment="$(sql "select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US') || '+05'")"
  sleep 2
  sql "insert into qd_proof_marker (label) values ('after-the-moment')" > /dev/null
  archive_now || fail "the WAL segment did not reach the bucket"
  step pitr 0 single pitr "$moment"
  expect "the copy has what was written before $moment and not what came after" \
    [ "$(dc exec -T db-scratch psql -X -qAt -U postgres -d qarz -c "select string_agg(label, ',' order by id) from qd_proof_marker where label like '%the-moment'" | tr -d '\r')" = "before-the-moment" ]
  expect "the live database has both" [ "$(sql "select count(*) from qd_proof_marker where label like '%the-moment'")" = 2 ]
  expect "the copy archives nothing" [ "$(dc exec -T db-scratch psql -X -qAt -U postgres -d qarz -c 'show archive_mode' | tr -d '\r')" = off ]
  step pitr-down 0 single pitr-down

  # ---------------------------------------------------------------------------------------------
  section "14. The machine is lost: the database volume destroyed, restored from the bucket alone"
  # Written after the last backup: only the WAL archive has these rows.
  sql "insert into qd_proof_marker (label) select 'after-last-backup-' || g from generate_series(1, 300) g" > /dev/null
  archive_now || fail "the WAL segment did not reach the bucket"
  local before after
  before="$(fingerprint)"
  echo "      before: $before"
  step restore-over-live-database 65 dc run --rm --no-deps restore restore
  expect "a restore over a volume that holds a database is refused and removes nothing" said restore-over-live-database "REFUSED"
  dc stop cloudflared proxy api worker backup files-backup db > /dev/null 2>&1
  dc rm --force db backup > /dev/null 2>&1
  docker volume rm "${PROJECT}_pgdata" > /dev/null
  expect "the database volume is gone" bash -c '! docker volume inspect "$1" > /dev/null 2>&1' _ "${PROJECT}_pgdata"
  step up-before-restore nonzero single up "$RELEASE"
  expect "starting an empty database in front of the bucket's backups is refused" said up-before-restore "REFUSED"
  expect "and no database was created by the attempt" volume_is_empty "${PROJECT}_pgdata"
  step restore-with-wrong-passphrase nonzero dc run --rm --no-deps -e QD_BACKUP_PASSPHRASE=not-the-passphrase restore restore
  expect "the wrong passphrase restored nothing" volume_is_empty "${PROJECT}_pgdata"
  step restore 0 single restore
  step up-after-restore 0 single up "$RELEASE"
  after="$(fingerprint)"
  echo "      after:  $after"
  expect "the data is back, the rows written after the last backup included" [ "$before" = "$after" ]
  expect "the application answers through the tunnel's place again" \
    bash -c 'grep -q "\"ok\"" <<< "$1"' _ "$(in_tunnel curl -sS -H 'X-Forwarded-Proto: https' -H "CF-Connecting-IP: $VISITOR_B" http://proxy:8080/healthz || true)"
  expect "the three roles can sign in with the passwords of the env file (the API is healthy, the worker stays up)" \
    bash -c '[ "$1" = "running 0" ]' _ "$(docker inspect --format '{{.State.Status}} {{.RestartCount}}' "$(dc ps --quiet worker)" 2>/dev/null)"
  expect "the restored database archives again, on a new timeline" archive_now
  expect "it is on timeline 2" [ "$(sql "select timeline_id from pg_control_checkpoint()")" = 2 ]
  step backup-after-restore 0 single backup full
  step restore-test-after-restore 0 single restore-test
  expect_field outcome ok
  step check-after-restore 0 job check

  # ---------------------------------------------------------------------------------------------
  section "15. Everything stops, and is started in the worst order (what Docker does after the machine restarts)"
  # Docker restarts containers without regard for what depends on what: the tunnel before the proxy,
  # the API before the database. Nothing here runs `compose up`, which would put them in order.
  local service
  dc stop cloudflared proxy worker api files-backup backup db > /dev/null 2>&1
  for service in cloudflared proxy worker api files-backup backup db; do
    docker start "$(dc ps --all --quiet "$service")" > /dev/null
  done
  answers() {
    in_tunnel curl -fsS -H 'X-Forwarded-Proto: https' -H "CF-Connecting-IP: $VISITOR_B" http://proxy:8080/healthz | grep -q '"ok"'
  }
  expect "the application answers again without anybody running a command" wait_for 180 answers
  expect "the data is as it was" [ "$(fingerprint)" = "$after" ]
  expect "the worker is running" [ "$(docker inspect --format '{{.State.Status}}' "$(dc ps --quiet worker)" 2>/dev/null)" = running ]
  expect "the write-ahead log reaches the bucket again" archive_now
  # The scheduler is back when it has checked the repository again, by itself.
  local checked
  checked="$(dc exec -T backup cat /var/lib/qarz-backup/check.status | tr -d '\r')"
  expect "the scheduler runs its checks again, and they pass" \
    wait_for 120 bash -c '[ "$(MSYS_NO_PATHCONV=1 docker exec "$1" cat /var/lib/qarz-backup/check.status | tr -d "\r")" != "$2" ] && MSYS_NO_PATHCONV=1 docker exec "$1" /opt/qarz-single/healthcheck.sh' _ "$(dc ps --quiet backup)" "$checked"

  printf '\n== Result: %s passed, %s failed, in %s s\n' "$passes" "$failures" "$(($(date +%s) - started))"
  [ "$failures" = 0 ]
}

case "${1:-}" in
  up) up ;;
  run) run ;;
  down) down ;;
  logs) load_state; dc logs --no-color --tail "${2:-60}" ;;
  all)
    up
    code=0
    (run) || code=$?
    down
    exit "$code"
    ;;
  *) die "usage: single-host-proof.sh up | run | down | all | logs [lines]" ;;
esac
