"""One error shape for the whole API, with the message in the caller's language (REQ-N01)."""

from fastapi import Request
from fastapi.responses import JSONResponse

from qarz.application.errors import AppError

_STATUS = {
    "UNAUTHENTICATED": 401,
    "NOT_FOUND": 404,
    "FORBIDDEN_ROLE": 403,
    "VALIDATION": 422,
    "IDEMPOTENCY_KEY_REUSED": 409,
    "ALREADY_MEMBER": 409,
    "OWNER_MEMBERSHIP_FIXED": 409,
    "TRANSFER_PENDING": 409,
    "TRANSFER_TARGET_INVALID": 409,
    "NOT_TRANSFER_TARGET": 409,
    "SUBSCRIPTION_LIMITED": 402,
    "SHOP_SUSPENDED": 403,
    "RATE_LIMITED": 429,
    "CUSTOMER_ARCHIVED": 409,
    "CUSTOMER_HAS_BALANCE": 409,
    "EXCEEDS_BALANCE": 409,
    "ALREADY_REVERSED": 409,
    "CANNOT_REVERSE_REVERSAL": 409,
    "WOULD_GO_NEGATIVE": 409,
    "PROMISE_ALREADY_SET": 409,
    "CUSTOMER_ALREADY_LINKED": 409,
    "DISPUTE_NOT_ALLOWED": 409,
    "DELETION_ALREADY_REQUESTED": 409,
    "DELETION_NOT_REQUESTED": 409,
    "ONLINE_PAY_OFF": 409,
    "LIMIT_REACHED": 409,
    "REMINDERS_OFF": 409,
    "REMINDER_NOT_DUE": 409,
    "REMINDER_LIMIT_REACHED": 409,
    "CUSTOMER_UNREACHABLE": 409,
    "REQUEST_ALREADY_OPEN": 409,
    "DATE_REQUEST_NOT_ALLOWED": 409,
    "PROMISE_NOT_CHANGEABLE": 409,
    "CATALOG_NAME_TAKEN": 409,
    "CATALOG_ITEM_NOT_LEARNED": 409,
    "CATALOG_MERGE_TARGET_INVALID": 409,
    "LINES_ALREADY_ADDED": 409,
    "LINES_SUM_MISMATCH": 409,
    "LINES_WINDOW_CLOSED": 409,
    "PAYMENT_NOTICE_NOT_ALLOWED": 409,
    "PAYMENT_NOTICE_NOT_OPEN": 409,
    "FILE_STORE_UNAVAILABLE": 503,
}

_MESSAGES = {
    "uz": {
        "UNAUTHENTICATED": "Avval tizimga kiring.",
        "NOT_FOUND": "Topilmadi.",
        "FORBIDDEN_ROLE": "Bu amal uchun sizning rolingiz yetarli emas.",
        "VALIDATION": "Ma'lumotlar noto'g'ri kiritilgan.",
        "IDEMPOTENCY_KEY_REUSED": "Bu so'rov kaliti boshqa amal uchun ishlatilgan.",
        "ALREADY_MEMBER": "Siz allaqachon shu do'kon xodimisiz.",
        "OWNER_MEMBERSHIP_FIXED": "Do'kon egasining a'zoligi faqat egalikni o'tkazish orqali o'zgaradi.",
        "TRANSFER_PENDING": "Egalikni o'tkazish taklifi allaqachon javob kutmoqda.",
        "TRANSFER_TARGET_INVALID": "Egalikni faqat shu do'konning faol menejeriga o'tkazish mumkin.",
        "NOT_TRANSFER_TARGET": "Bu taklifga faqat taklif qilingan menejer javob bera oladi.",
        "SUBSCRIPTION_LIMITED": "Obuna tugagan: yangi nasiya yozilmaydi. To'lov qabul qilish va ko'rish ishlayveradi.",
        "SHOP_SUSPENDED": "Do'kon to'xtatilgan. Faqat do'kon egasi ma'lumotlarni ko'ra oladi va eksport qila oladi.",
        "CUSTOMER_ARCHIVED": "Bu mijoz arxivda. Avval arxivdan chiqaring.",
        "CUSTOMER_HAS_BALANCE": "Qarzi bor mijozni arxivlab bo'lmaydi.",
        "EXCEEDS_BALANCE": "To'lov mijozning qarzidan katta bo'lishi mumkin emas.",
        "ALREADY_REVERSED": "Bu yozuv allaqachon bekor qilingan.",
        "CANNOT_REVERSE_REVERSAL": "Bekor qilish yozuvini bekor qilib bo'lmaydi.",
        "WOULD_GO_NEGATIVE": "Bekor qilinsa qarz manfiy bo'lib qoladi. Avval keyingi to'lovni bekor qiling.",
        "PROMISE_ALREADY_SET": "Muddat allaqachon belgilangan. Endi uni menejer yoki do'kon egasi o'zgartiradi.",
        "CATALOG_NAME_TAKEN": "Katalogda shu nomli mahsulot bor (yashirilgan bo'lishi ham mumkin).",
        "CATALOG_ITEM_NOT_LEARNED": "Bu mahsulot allaqachon ko'rib chiqilgan.",
        "CATALOG_MERGE_TARGET_INVALID": "Faqat katalogda ko'rinadigan, ko'rib chiqilgan mahsulotga birlashtiriladi.",
        "CUSTOMER_ALREADY_LINKED": "Bu mijoz allaqachon Telegram hisobiga ulangan.",
        "DISPUTE_NOT_ALLOWED": "Bu yozuv bo'yicha e'tiroz bildirib bo'lmaydi yoki u allaqachon ko'rib chiqilgan.",
        "REQUEST_ALREADY_OPEN": "Bu yozuv bo'yicha muddatni ko'chirish so'rovi allaqachon ko'rib chiqilmoqda.",
        "DATE_REQUEST_NOT_ALLOWED": "Bu yozuv muddatini ko'chirish so'rovini hozir qabul qilib bo'lmaydi.",
        "PROMISE_NOT_CHANGEABLE": "Bu yozuvning to'lash muddati yo'q yoki yozuv bekor qilingan.",
        "LINES_ALREADY_ADDED": "Bu yozuvga mahsulotlar allaqachon qo'shilgan.",
        "LINES_SUM_MISMATCH": "Mahsulotlar yig'indisi yozuv summasiga teng emas.",
        "LINES_WINDOW_CLOSED": "Mahsulot qo'shish muddati o'tgan: bu faqat sotuvdan keyingi kun oxirigacha mumkin.",
        "REMINDERS_OFF": "Eslatmalar do'kon yoki shu mijoz uchun o'chirilgan.",
        "REMINDER_NOT_DUE": "Bu mijozda muddati o'tgan yoki bugun to'lanadigan qarz yo'q.",
        "REMINDER_LIMIT_REACHED": "Bu mijozga bugun eslatma allaqachon yuborilgan. Kuniga bitta mumkin.",
        "CUSTOMER_UNREACHABLE": "Bu mijozga yetib bo'lmaydi: Telegram ulanmagan, SMS esa o'chiq yoki raqam yo'q.",
        "LIMIT_REACHED": "Bu savdo mijozning nasiya limitidan oshadi. Menejer yoki do'kon egasi yoza oladi.",
        "DELETION_ALREADY_REQUESTED": "Do'konni o'chirish allaqachon so'ralgan.",
        "DELETION_NOT_REQUESTED": "Do'konni o'chirish so'ralmagan.",
        "PAYMENT_NOTICE_NOT_ALLOWED": "Ko'rib chiqilmagan to'lov xabarlaringiz juda ko'p. Do'kon javobini kuting.",
        "PAYMENT_NOTICE_NOT_OPEN": "Bu to'lov xabari allaqachon ko'rib chiqilgan yoki muddati o'tgan.",
        "FILE_STORE_UNAVAILABLE": "Fayllarni saqlash hozir ishlamayapti. Birozdan keyin qayta urinib ko'ring.",
        "ONLINE_PAY_OFF": "Onlayn to'lov hozircha yoqilmagan. Karta orqali to'lash: /obuna",
        "RATE_LIMITED": "So'rovlar juda ko'p. Biroz kutib, qayta urinib ko'ring.",
        "ERROR": "Xatolik yuz berdi.",
    },
    "ru": {
        "UNAUTHENTICATED": "Сначала войдите в систему.",
        "NOT_FOUND": "Не найдено.",
        "FORBIDDEN_ROLE": "Вашей роли недостаточно для этого действия.",
        "VALIDATION": "Данные введены неверно.",
        "IDEMPOTENCY_KEY_REUSED": "Этот ключ запроса уже использован для другого действия.",
        "ALREADY_MEMBER": "Вы уже сотрудник этого магазина.",
        "OWNER_MEMBERSHIP_FIXED": "Участие владельца меняется только через передачу магазина.",
        "TRANSFER_PENDING": "Предложение о передаче магазина уже ожидает ответа.",
        "TRANSFER_TARGET_INVALID": "Магазин можно передать только активному менеджеру этого магазина.",
        "NOT_TRANSFER_TARGET": "Ответить на предложение может только менеджер, которому оно адресовано.",
        "SUBSCRIPTION_LIMITED": "Подписка истекла: новые продажи в долг недоступны. Оплаты и просмотр работают.",
        "SHOP_SUSPENDED": "Магазин временно приостановлен. Только владелец может просматривать и выгружать данные.",
        "CUSTOMER_ARCHIVED": "Этот клиент в архиве. Сначала верните его из архива.",
        "CUSTOMER_HAS_BALANCE": "Клиента с долгом нельзя отправить в архив.",
        "EXCEEDS_BALANCE": "Оплата не может быть больше долга клиента.",
        "ALREADY_REVERSED": "Эта запись уже отменена.",
        "CANNOT_REVERSE_REVERSAL": "Запись об отмене отменить нельзя.",
        "WOULD_GO_NEGATIVE": "После такой отмены долг стал бы отрицательным. Сначала отмените более позднюю оплату.",
        "PROMISE_ALREADY_SET": "Срок уже задан. Теперь его меняет менеджер или владелец магазина.",
        "CATALOG_NAME_TAKEN": "В каталоге уже есть товар с таким названием (возможно, он скрыт).",
        "CATALOG_ITEM_NOT_LEARNED": "Этот товар уже проверен.",
        "CATALOG_MERGE_TARGET_INVALID": "Объединить можно только с проверенным товаром, который виден в каталоге.",
        "CUSTOMER_ALREADY_LINKED": "Этот клиент уже подключён к аккаунту Telegram.",
        "DISPUTE_NOT_ALLOWED": "По этой записи нельзя подать возражение, или оно уже рассмотрено.",
        "REQUEST_ALREADY_OPEN": "Просьба о переносе срока по этой записи уже рассматривается.",
        "DATE_REQUEST_NOT_ALLOWED": "Просьбу о переносе срока по этой записи сейчас принять нельзя.",
        "PROMISE_NOT_CHANGEABLE": "У этой записи нет срока оплаты, или она отменена.",
        "LINES_ALREADY_ADDED": "К этой записи товары уже добавлены.",
        "LINES_SUM_MISMATCH": "Сумма товаров не равна сумме записи.",
        "LINES_WINDOW_CLOSED": "Срок добавления товаров истёк: это возможно только до конца дня после продажи.",
        "REMINDERS_OFF": "Напоминания выключены для магазина или для этого клиента.",
        "REMINDER_NOT_DUE": "У этого клиента нет просроченного долга и долга со сроком сегодня.",
        "REMINDER_LIMIT_REACHED": "Этому клиенту сегодня уже отправлено напоминание. Можно одно в день.",
        "CUSTOMER_UNREACHABLE": "С этим клиентом нет связи: Telegram не подключён, а SMS выключены или нет номера.",
        "LIMIT_REACHED": "Эта продажа превысит лимит клиента. Записать может менеджер или владелец.",
        "DELETION_ALREADY_REQUESTED": "Удаление магазина уже запрошено.",
        "DELETION_NOT_REQUESTED": "Удаление магазина не запрашивалось.",
        "PAYMENT_NOTICE_NOT_ALLOWED": "У вас слишком много нерассмотренных сообщений об оплате. Дождитесь ответа.",
        "PAYMENT_NOTICE_NOT_OPEN": "Это сообщение об оплате уже рассмотрено или его срок истёк.",
        "FILE_STORE_UNAVAILABLE": "Хранилище файлов сейчас недоступно. Попробуйте ещё раз чуть позже.",
        "ONLINE_PAY_OFF": "Онлайн-оплата пока не включена. Оплата переводом на карту: /obuna",
        "RATE_LIMITED": "Слишком много запросов. Подождите немного и повторите.",
        "ERROR": "Произошла ошибка.",
    },
}


def error_response(code: str, lang: str, fields: dict[str, str] | None = None) -> JSONResponse:
    messages = _MESSAGES.get(lang, _MESSAGES["uz"])
    body = {"error": {"code": code, "message": messages.get(code, messages["ERROR"]), "fields": fields or {}}}
    return JSONResponse(body, status_code=_STATUS.get(code, 500))


async def app_error_handler(request: Request, exc: Exception) -> JSONResponse:
    assert isinstance(exc, AppError)
    lang = getattr(request.state, "lang", "uz")
    response = error_response(exc.code, lang, exc.fields)
    retry_after = getattr(exc, "retry_after", None)
    if retry_after is not None:
        response.headers["Retry-After"] = str(retry_after)
    return response
