"""Words of the export workbook (ADR-021: interface text lives in catalogs).

Uzbek defines the keys; `tests/test_export_texts.py` requires Russian to mirror them, list for list. The
other languages may trail behind and read Uzbek where they do (`qarz.application.chat_texts` says how).
"""

from collections.abc import Mapping
from functools import cache

from qarz.application import texts_en, texts_kaa, texts_tg
from qarz.domain import languages
from qarz.domain.uz_cyrillic import to_cyrillic

UZ: dict[str, str | tuple[str, ...]] = {
    "sheet_summary": "Hisobot",
    "sheet_customers": "Mijozlar",
    "sheet_ledger": "Daftar",
    "sheet_promises": "Muddatlar tarixi",
    "sheet_goods": "Mahsulotlar",
    # Only in the workbook of a shop that has a cash book.
    "sheet_cash": "Kassa",
    "cash": (
        "Kun",
        "Yozilgan vaqt",
        "Yo'nalish",
        "To'lov usuli",
        "Valyuta",
        "Summa",
        "Toifa",
        "Izoh",
        "Bekor qilinganmi",
        "Bekor qilish sababi",
        "Kim yozgan",
        "Xodim ID",
        "Daftardagi to'lov (ID)",
        "Yozuv ID",
    ),
    "cash_income": "Kirim",
    "cash_expense": "Chiqim",
    "cash_cash": "Naqd",
    "cash_card": "Karta",
    "cash_transfer": "O'tkazma",
    # An export of one period of the cash book (`qarz.application.cash_export`).
    "cash_period": (
        "Kun",
        "Yozilgan vaqt",
        "Yo'nalish",
        "To'lov usuli",
        "Valyuta",
        "Summa",
        "Toifa",
        "Izoh",
        "Manba",
        "Bekor qilinganmi",
        "Bekor qilish sababi",
        "Bekor qilingan vaqt",
        "Xodim ID",
        "Yozuv ID",
    ),
    "cash_customer": "Mijoz",
    "cash_source_manual": "Qo'lda yozilgan",
    "cash_source_ledger": "Mijoz to'lovi",
    "cash_source_stock": "Ombor",
    "cash_reversed": "Mijozning to'lovi bekor qilindi",
    "cash_period_from": "Davr boshi",
    "cash_period_to": "Davr oxiri",
    "cash_entries_count": "Yozuvlar soni (bekor qilinganlari bilan)",
    "cash_balances_title": "Qoldiqlar",
    "cash_balances": (
        "Valyuta",
        "To'lov usuli",
        "Davr boshida",
        "Kirim",
        "Chiqim",
        "Davr oxirida",
        "Yozuvlar",
    ),
    "cash_all_methods": "Jami",
    "cash_categories_title": "Toifalar bo'yicha",
    "cash_categories": (
        "Valyuta",
        "Yo'nalish",
        "Toifa",
        "Summa",
        "Yozuvlar",
    ),
    "cash_summary_note": (
        "Bekor qilingan yozuvlar hisobga kirmaydi. So'm va dollar alohida hisoblanadi: ular hech qachon qo'shilmaydi."
    ),
    "customers": ("Mijoz", "Telefon", "Holati", "Nasiya limiti", "Qarzi", "Qo'shilgan sana", "Mijoz ID"),
    "ledger": (
        "Sana va vaqt",
        "Mijoz",
        "Turi",
        "Summa",
        "Qarzga ta'siri",
        "Izoh",
        "To'lash muddati",
        "Bekor qilinganmi",
        "Bekor qilgan yozuvi (ID)",
        "Kim yozgan",
        "Xodim ID",
        "Mijozdagi tartib raqami",
        "Yozuv ID",
        "Mijoz ID",
    ),
    "promises": ("Yozuv ID", "Mijoz", "To'lash muddati", "Belgilangan vaqt", "Kim belgilagan", "Sabab"),
    "goods": ("Yozuv ID", "Sana va vaqt", "Mijoz", "Qator", "Mahsulot", "Miqdor", "Birlik", "Narxi", "Jami"),
    "months": (
        "Oy",
        "Nasiya summasi",
        "Nasiya soni",
        "Boshlang'ich qarz summasi",
        "To'lovlar summasi",
        "To'lovlar soni",
        "Bekor qilingan yozuvlar soni",
    ),
    "summary_shop": "Do'kon",
    "summary_made": "Eksport vaqti (Toshkent)",
    "summary_customers": "Mijozlar soni",
    "summary_debtors": "Qarzdor mijozlar soni",
    "summary_outstanding": "Jami qarz",
    # Only in the workbook of a shop that has dollar entries: its so'm figures stay where they were, and
    # the dollar ones are further columns and further rows, never part of a so'm total.
    "currency": "Valyuta",
    "limit_usd": "Nasiya limiti ($)",
    "owed_usd": "Qarzi ($)",
    "summary_debtors_usd": "Dollarda qarzdor mijozlar soni",
    "summary_outstanding_usd": "Jami qarz ($)",
    "summary_months_usd": (
        "Oylar bo'yicha, dollarda (bekor qilingan yozuvlar va bekor qilish yozuvlari hisobga olinmagan)"
    ),
    "summary_entries": "Daftardagi yozuvlar soni",
    "summary_months": "Oylar bo'yicha (bekor qilingan yozuvlar va bekor qilish yozuvlari hisobga olinmagan)",
    "kind_credit": "Nasiya",
    "kind_opening": "Boshlang'ich qarz",
    "kind_payment": "To'lov",
    "kind_reversal": "Bekor qilish",
    "status_active": "Faol",
    "status_archived": "Arxivda",
    "status_anonymized": "Ma'lumotlari o'chirilgan",
    "role_seller": "Sotuvchi",
    "role_manager": "Menejer",
    "role_owner": "Do'kon egasi",
    "actor_default": "Do'kon bo'yicha odatiy muddat",
    "actor_staff": "Xodim",
    "actor_customer_request": "Mijoz so'rovi bilan",
    "yes": "Ha",
    "no": "Yo'q",
    # The stock and the suppliers (expansion module I): only in the workbook of a shop that has any.
    "sheet_stock": "Ombor",
    "sheet_stock_movements": "Ombor harakatlari",
    "sheet_stock_documents": "Ombor hujjatlari",
    "sheet_suppliers": "Ta'minotchilar",
    "sheet_supplier_entries": "Ta'minotchi hisobi",
    "stock": (
        "Tovar",
        "Birlik",
        "Sotuv narxi",
        "Qoldiq",
        "Kam qoldiq chegarasi",
        "Tannarx valyutasi",
        "O'rtacha tannarx",
        "Qoldiq qiymati (tannarxda)",
        "Shtrix-kodlar",
        "Tovar ID",
    ),
    "stock_movements": (
        "Sana va vaqt",
        "Tovar",
        "Turi",
        "Miqdor",
        "Birlik",
        "Harakatdan keyingi qoldiq",
        "Tannarx (jami)",
        "Valyuta",
        "Sotuv summasi",
        "Sabab",
        "Hujjat",
        "Bekor qilinganmi",
        "Harakat ID",
        "Tovar ID",
    ),
    "stock_documents": (
        "Raqam",
        "Turi",
        "Holati",
        "Sana",
        "Ta'minotchi",
        "Mijoz",
        "Valyuta",
        "Jami",
        "To'langan",
        "Sabab",
        "Izoh",
        "Bekor qilish sababi",
        "Hujjat ID",
    ),
    "suppliers": ("Ta'minotchi", "Telefon", "Izoh", "Holati", "Qarzimiz (so'm)", "Qarzimiz ($)", "Ta'minotchi ID"),
    "supplier_entries": (
        "Sana va vaqt",
        "Ta'minotchi",
        "Turi",
        "Summa",
        "Valyuta",
        "Qarzga ta'siri",
        "Izoh",
        "Bekor qilinganmi",
        "Hujjat",
        "Yozuv ID",
        "Ta'minotchi ID",
    ),
    "movement_receipt": "Kirim",
    "movement_sale": "Sotuv",
    "movement_customer_return": "Mijozdan qaytdi",
    "movement_supplier_return": "Ta'minotchiga qaytarildi",
    "movement_write_off": "Hisobdan chiqarildi",
    "movement_correction": "Inventarizatsiya tuzatishi",
    "movement_reversal": "Bekor qilish",
    "document_receipt": "Kirim",
    "document_customer_return": "Mijozdan qaytarish",
    "document_supplier_return": "Ta'minotchiga qaytarish",
    "document_write_off": "Hisobdan chiqarish",
    "document_stocktake": "Inventarizatsiya",
    "document_draft": "Qoralama",
    "document_posted": "O'tkazilgan",
    "document_cancelled": "Bekor qilingan",
    "reason_damaged": "Shikastlangan",
    "reason_expired": "Muddati o'tgan",
    "reason_lost": "Yo'qolgan",
    "reason_own_use": "O'z ehtiyojiga",
    "supplier_purchase": "Tovar olindi",
    "supplier_opening": "Boshlang'ich qarz",
    "supplier_payment": "To'lov",
    "supplier_return": "Tovar qaytarildi",
    "supplier_reversal": "Bekor qilish",
}

RU: dict[str, str | tuple[str, ...]] = {
    "sheet_summary": "Отчёт",
    "sheet_customers": "Клиенты",
    "sheet_ledger": "Книга",
    "sheet_promises": "История сроков",
    "sheet_goods": "Товары",
    "sheet_cash": "Касса",
    "cash": (
        "День",
        "Время записи",
        "Направление",
        "Способ оплаты",
        "Валюта",
        "Сумма",
        "Статья",
        "Примечание",
        "Отменена",
        "Причина отмены",
        "Кто записал",
        "ID сотрудника",
        "Оплата в книге (ID)",
        "ID записи",
    ),
    "cash_income": "Приход",
    "cash_expense": "Расход",
    "cash_cash": "Наличные",
    "cash_card": "Карта",
    "cash_transfer": "Перевод",
    # An export of one period of the cash book (`qarz.application.cash_export`).
    "cash_period": (
        "День",
        "Время записи",
        "Направление",
        "Способ оплаты",
        "Валюта",
        "Сумма",
        "Статья",
        "Примечание",
        "Источник",
        "Отменена",
        "Причина отмены",
        "Время отмены",
        "ID сотрудника",
        "ID записи",
    ),
    "cash_customer": "Клиент",
    "cash_source_manual": "Записано вручную",
    "cash_source_ledger": "Оплата клиента",
    "cash_source_stock": "Склад",
    "cash_reversed": "Оплата клиента была отменена",
    "cash_period_from": "Начало периода",
    "cash_period_to": "Конец периода",
    "cash_entries_count": "Число записей (вместе с отменёнными)",
    "cash_balances_title": "Остатки",
    "cash_balances": (
        "Валюта",
        "Способ оплаты",
        "На начало периода",
        "Приход",
        "Расход",
        "На конец периода",
        "Записи",
    ),
    "cash_all_methods": "Итого",
    "cash_categories_title": "По статьям",
    "cash_categories": (
        "Валюта",
        "Направление",
        "Статья",
        "Сумма",
        "Записи",
    ),
    "cash_summary_note": (
        "Отменённые записи не учитываются. Сумы и доллары считаются отдельно: они никогда не складываются."
    ),
    "customers": ("Клиент", "Телефон", "Состояние", "Лимит долга", "Долг", "Дата добавления", "ID клиента"),
    "ledger": (
        "Дата и время",
        "Клиент",
        "Вид",
        "Сумма",
        "Влияние на долг",
        "Заметка",
        "Срок оплаты",
        "Отменена ли",
        "Какую запись отменяет (ID)",
        "Кто записал",
        "ID сотрудника",
        "Номер у клиента",
        "ID записи",
        "ID клиента",
    ),
    "promises": ("ID записи", "Клиент", "Срок оплаты", "Когда задан", "Кто задал", "Причина"),
    "goods": ("ID записи", "Дата и время", "Клиент", "Строка", "Товар", "Количество", "Единица", "Цена", "Итого"),
    "months": (
        "Месяц",
        "Сумма продаж в долг",
        "Число продаж в долг",
        "Сумма начальных долгов",
        "Сумма оплат",
        "Число оплат",
        "Число отменённых записей",
    ),
    "summary_shop": "Магазин",
    "summary_made": "Время выгрузки (Ташкент)",
    "summary_customers": "Число клиентов",
    "summary_debtors": "Число должников",
    "summary_outstanding": "Всего долг",
    "currency": "Валюта",
    "limit_usd": "Лимит долга ($)",
    "owed_usd": "Долг ($)",
    "summary_debtors_usd": "Число должников в долларах",
    "summary_outstanding_usd": "Всего долг ($)",
    "summary_months_usd": "По месяцам, в долларах (отменённые записи и записи об отмене не учтены)",
    "summary_entries": "Число записей в книге",
    "summary_months": "По месяцам (отменённые записи и записи об отмене не учтены)",
    "kind_credit": "Продажа в долг",
    "kind_opening": "Начальный долг",
    "kind_payment": "Оплата",
    "kind_reversal": "Отмена",
    "status_active": "Активен",
    "status_archived": "В архиве",
    "status_anonymized": "Данные удалены",
    "role_seller": "Продавец",
    "role_manager": "Менеджер",
    "role_owner": "Владелец",
    "actor_default": "Срок магазина по умолчанию",
    "actor_staff": "Сотрудник",
    "actor_customer_request": "По просьбе клиента",
    "yes": "Да",
    "no": "Нет",
    "sheet_stock": "Склад",
    "sheet_stock_movements": "Движения склада",
    "sheet_stock_documents": "Документы склада",
    "sheet_suppliers": "Поставщики",
    "sheet_supplier_entries": "Расчёты с поставщиками",
    "stock": (
        "Товар",
        "Единица",
        "Цена продажи",
        "Остаток",
        "Порог малого остатка",
        "Валюта себестоимости",
        "Средняя себестоимость",
        "Стоимость остатка (по себестоимости)",
        "Штрихкоды",
        "ID товара",
    ),
    "stock_movements": (
        "Дата и время",
        "Товар",
        "Вид",
        "Количество",
        "Единица",
        "Остаток после движения",
        "Себестоимость (всего)",
        "Валюта",
        "Сумма продажи",
        "Причина",
        "Документ",
        "Отменено ли",
        "ID движения",
        "ID товара",
    ),
    "stock_documents": (
        "Номер",
        "Вид",
        "Состояние",
        "Дата",
        "Поставщик",
        "Клиент",
        "Валюта",
        "Итого",
        "Оплачено",
        "Причина",
        "Заметка",
        "Причина отмены",
        "ID документа",
    ),
    "suppliers": ("Поставщик", "Телефон", "Заметка", "Состояние", "Наш долг (сум)", "Наш долг ($)", "ID поставщика"),
    "supplier_entries": (
        "Дата и время",
        "Поставщик",
        "Вид",
        "Сумма",
        "Валюта",
        "Влияние на долг",
        "Заметка",
        "Отменена ли",
        "Документ",
        "ID записи",
        "ID поставщика",
    ),
    "movement_receipt": "Приход",
    "movement_sale": "Продажа",
    "movement_customer_return": "Возврат от клиента",
    "movement_supplier_return": "Возврат поставщику",
    "movement_write_off": "Списание",
    "movement_correction": "Поправка инвентаризации",
    "movement_reversal": "Отмена",
    "document_receipt": "Приход",
    "document_customer_return": "Возврат от клиента",
    "document_supplier_return": "Возврат поставщику",
    "document_write_off": "Списание",
    "document_stocktake": "Инвентаризация",
    "document_draft": "Черновик",
    "document_posted": "Проведён",
    "document_cancelled": "Отменён",
    "reason_damaged": "Повреждён",
    "reason_expired": "Истёк срок",
    "reason_lost": "Утерян",
    "reason_own_use": "Для себя",
    "supplier_purchase": "Получен товар",
    "supplier_opening": "Начальный долг",
    "supplier_payment": "Оплата",
    "supplier_return": "Возврат товара",
    "supplier_reversal": "Отмена",
}

# Uzbek Cyrillic entries written by hand; the rest is the Uzbek entry transliterated (see `_entry`).
UZ_CYRILLIC: dict[str, str | tuple[str, ...]] = {}

# What each language has of its own. Uzbek and Russian are complete; the others may lack keys.
CATALOGS: Mapping[str, Mapping[str, str | tuple[str, ...]]] = {
    "uz": UZ,
    languages.UZ_CYRILLIC: UZ_CYRILLIC,
    "ru": RU,
    "tg": texts_tg.EXPORT,
    "kaa": texts_kaa.EXPORT,
    "en": texts_en.EXPORT,
}


@cache
def _entry(lang: str, key: str) -> str | tuple[str, ...] | None:
    """A language's own entry; without one the Uzbek entry, transliterated for Uzbek Cyrillic."""
    own = CATALOGS.get(lang, UZ).get(key)
    if own is not None:
        return own
    source = UZ.get(key)
    if source is None or lang != languages.UZ_CYRILLIC:
        return source
    return to_cyrillic(source) if isinstance(source, str) else tuple(to_cyrillic(title) for title in source)


def word(lang: str, key: str, fallback: str | None = None) -> str:
    """One word or phrase. A language without it reads Uzbek; an unknown key reads `fallback` when given."""
    value = _entry(lang, key)
    if value is None:
        value = fallback
    if not isinstance(value, str):
        raise KeyError(key)
    return value


def header(lang: str, key: str) -> tuple[str, ...]:
    value = _entry(lang, key)
    if value is None or isinstance(value, str):
        raise KeyError(key)
    return value
