"""Words of the export workbook (ADR-021: interface text lives in catalogs).

Uzbek defines the keys; `tests/test_export_texts.py` requires Russian to mirror them, list for list. The
other languages may trail behind and read Uzbek where they do (`qarz.application.chat_texts` says how).
"""

from collections.abc import Mapping
from functools import cache

from qarz.application import texts_en, texts_kaa, texts_tg
from qarz.domain import languages
from qarz.domain.uz_cyrillic import to_cyrillic

UZ: dict[str, str | tuple[str, ...]] = {
    "sheet_summary": "Hisobot",
    "sheet_customers": "Mijozlar",
    "sheet_ledger": "Daftar",
    "sheet_promises": "Muddatlar tarixi",
    "sheet_goods": "Mahsulotlar",
    # Only in the workbook of a shop that has a cash book.
    "sheet_cash": "Kassa",
    "cash": (
        "Kun",
        "Yozilgan vaqt",
        "Yo'nalish",
        "To'lov usuli",
        "Valyuta",
        "Summa",
        "Toifa",
        "Izoh",
        "Bekor qilinganmi",
        "Bekor qilish sababi",
        "Kim yozgan",
        "Xodim ID",
        "Daftardagi to'lov (ID)",
        "Yozuv ID",
    ),
    "cash_income": "Kirim",
    "cash_expense": "Chiqim",
    "cash_cash": "Naqd",
    "cash_card": "Karta",
    "cash_transfer": "O'tkazma",
    # An export of one period of the cash book (`qarz.application.cash_export`).
    "cash_period": (
        "Kun",
        "Yozilgan vaqt",
        "Yo'nalish",
        "To'lov usuli",
        "Valyuta",
        "Summa",
        "Toifa",
        "Izoh",
        "Manba",
        "Bekor qilinganmi",
        "Bekor qilish sababi",
        "Bekor qilingan vaqt",
        "Xodim ID",
        "Yozuv ID",
    ),
    "cash_customer": "Mijoz",
    "cash_source_manual": "Qo'lda yozilgan",
    "cash_source_ledger": "Mijoz to'lovi",
    "cash_source_stock": "Ombor",
    "cash_reversed": "Mijozning to'lovi bekor qilindi",
    "cash_period_from": "Davr boshi",
    "cash_period_to": "Davr oxiri",
    "cash_entries_count": "Yozuvlar soni (bekor qilinganlari bilan)",
    "cash_balances_title": "Qoldiqlar",
    "cash_balances": (
        "Valyuta",
        "To'lov usuli",
        "Davr boshida",
        "Kirim",
        "Chiqim",
        "Davr oxirida",
        "Yozuvlar",
    ),
    "cash_all_methods": "Jami",
    "cash_categories_title": "Toifalar bo'yicha",
    "cash_categories": (
        "Valyuta",
        "Yo'nalish",
        "Toifa",
        "Summa",
        "Yozuvlar",
    ),
    "cash_summary_note": (
        "Bekor qilingan yozuvlar hisobga kirmaydi. So'm va dollar alohida hisoblanadi: ular hech qachon qo'shilmaydi."
    ),
    "customers": ("Mijoz", "Telefon", "Holati", "Nasiya limiti", "Qarzi", "Qo'shilgan sana", "Mijoz ID"),
    "ledger": (
        "Sana va vaqt",
        "Mijoz",
        "Turi",
        "Summa",
        "Qarzga ta'siri",
        "Izoh",
        "To'lash muddati",
        "Bekor qilinganmi",
        "Bekor qilgan yozuvi (ID)",
        "Kim yozgan",
        "Xodim ID",
        "Mijozdagi tartib raqami",
        "Yozuv ID",
        "Mijoz ID",
    ),
    "promises": ("Yozuv ID", "Mijoz", "To'lash muddati", "Belgilangan vaqt", "Kim belgilagan", "Sabab"),
    "goods": ("Yozuv ID", "Sana va vaqt", "Mijoz", "Qator", "Mahsulot", "Miqdor", "Birlik", "Narxi", "Jami"),
    "months": (
        "Oy",
        "Nasiya summasi",
        "Nasiya soni",
        "Boshlang'ich qarz summasi",
        "To'lovlar summasi",
        "To'lovlar soni",
        "Bekor qilingan yozuvlar soni",
    ),
    "summary_shop": "Do'kon",
    "summary_made": "Eksport vaqti (Toshkent)",
    "summary_customers": "Mijozlar soni",
    "summary_debtors": "Qarzdor mijozlar soni",
    "summary_outstanding": "Jami qarz",
    # Only in the workbook of a shop that has dollar entries: its so'm figures stay where they were, and
    # the dollar ones are further columns and further rows, never part of a so'm total.
    "currency": "Valyuta",
    "limit_usd": "Nasiya limiti ($)",
    "owed_usd": "Qarzi ($)",
    "summary_debtors_usd": "Dollarda qarzdor mijozlar soni",
    "summary_outstanding_usd": "Jami qarz ($)",
    "summary_advances": "Mijozlarning oldindan to'lovlari (avans)",
    "summary_advances_usd": "Mijozlarning oldindan to'lovlari ($)",
    "summary_months_usd": (
        "Oylar bo'yicha, dollarda (bekor qilingan yozuvlar va bekor qilish yozuvlari hisobga olinmagan)"
    ),
    "summary_entries": "Daftardagi yozuvlar soni",
    "summary_months": "Oylar bo'yicha (bekor qilingan yozuvlar va bekor qilish yozuvlari hisobga olinmagan)",
    "kind_credit": "Nasiya",
    "kind_opening": "Boshlang'ich qarz",
    "kind_payment": "To'lov",
    "kind_reversal": "Bekor qilish",
    "status_active": "Faol",
    "status_archived": "Arxivda",
    "status_anonymized": "Ma'lumotlari o'chirilgan",
    "role_seller": "Sotuvchi",
    "role_manager": "Menejer",
    "role_owner": "Do'kon egasi",
    "actor_default": "Do'kon bo'yicha odatiy muddat",
    "actor_staff": "Xodim",
    "actor_customer_request": "Mijoz so'rovi bilan",
    "yes": "Ha",
    "no": "Yo'q",
    # The stock and the suppliers (expansion module I): only in the workbook of a shop that has any.
    "sheet_stock": "Ombor",
    "sheet_stock_movements": "Ombor harakatlari",
    "sheet_stock_documents": "Ombor hujjatlari",
    "sheet_suppliers": "Ta'minotchilar",
    "sheet_supplier_entries": "Ta'minotchi hisobi",
    "stock": (
        "Tovar",
        "Birlik",
        "Sotuv narxi",
        "Qoldiq",
        "Kam qoldiq chegarasi",
        "Tannarx valyutasi",
        "O'rtacha tannarx",
        "Qoldiq qiymati (tannarxda)",
        "Shtrix-kodlar",
        "Tovar ID",
    ),
    "stock_movements": (
        "Sana va vaqt",
        "Tovar",
        "Turi",
        "Miqdor",
        "Birlik",
        "Harakatdan keyingi qoldiq",
        "Tannarx (jami)",
        "Valyuta",
        "Sotuv summasi",
        "Sabab",
        "Hujjat",
        "Bekor qilinganmi",
        "Harakat ID",
        "Tovar ID",
    ),
    "stock_documents": (
        "Raqam",
        "Turi",
        "Holati",
        "Sana",
        "Ta'minotchi",
        "Mijoz",
        "Valyuta",
        "Jami",
        "To'langan",
        "Sabab",
        "Izoh",
        "Bekor qilish sababi",
        "Hujjat ID",
    ),
    "suppliers": ("Ta'minotchi", "Telefon", "Izoh", "Holati", "Qarzimiz (so'm)", "Qarzimiz ($)", "Ta'minotchi ID"),
    "supplier_entries": (
        "Sana va vaqt",
        "Ta'minotchi",
        "Turi",
        "Summa",
        "Valyuta",
        "Qarzga ta'siri",
        "Izoh",
        "Bekor qilinganmi",
        "Hujjat",
        "Yozuv ID",
        "Ta'minotchi ID",
    ),
    "movement_receipt": "Kirim",
    "movement_sale": "Sotuv",
    "movement_customer_return": "Mijozdan qaytdi",
    "movement_supplier_return": "Ta'minotchiga qaytarildi",
    "movement_write_off": "Hisobdan chiqarildi",
    "movement_correction": "Inventarizatsiya tuzatishi",
    "movement_reversal": "Bekor qilish",
    "document_receipt": "Kirim",
    "document_customer_return": "Mijozdan qaytarish",
    "document_supplier_return": "Ta'minotchiga qaytarish",
    "document_write_off": "Hisobdan chiqarish",
    "document_stocktake": "Inventarizatsiya",
    "document_draft": "Qoralama",
    "document_posted": "O'tkazilgan",
    "document_cancelled": "Bekor qilingan",
    "reason_damaged": "Shikastlangan",
    "reason_expired": "Muddati o'tgan",
    "reason_lost": "Yo'qolgan",
    "reason_own_use": "O'z ehtiyojiga",
    "supplier_purchase": "Tovar olindi",
    "supplier_opening": "Boshlang'ich qarz",
    "supplier_payment": "To'lov",
    "supplier_return": "Tovar qaytarildi",
    "supplier_reversal": "Bekor qilish",
    # The network between shops (module J): four sheets, only in the workbook of a shop that has a link.
    "sheet_net_links": "Hamkorlar",
    "sheet_net_orders": "Hamkor buyurtmalari",
    "sheet_net_notes": "Yuk xatlari",
    "sheet_net_payments": "Hamkor to'lovlari",
    "net_links": ("Hamkor", "Telefon", "Biz", "Holati", "So'ralgan", "Tugagan", "Aloqa ID"),
    "net_orders": (
        "Hamkor",
        "Biz",
        "Buyurtma №",
        "Holati",
        "Yuborilgan",
        "Kerakli sana",
        "Izoh",
        "Valyuta",
        "Jami",
        "Qator",
        "Tovar",
        "Birlik",
        "So'ralgan",
        "Qabul qilingan",
        "Narx",
        "Sabab",
        "Buyurtma ID",
    ),
    "net_notes": (
        "Hamkor",
        "Biz",
        "Yuk xati №",
        "Buyurtma №",
        "Holati",
        "Berilgan",
        "Valyuta",
        "Jami",
        "To'langan",
        "Qator",
        "Tovar",
        "Birlik",
        "Miqdor",
        "Narx",
        "Summa",
        "Rad etish sababi",
        "Tuzatish sababi",
        "Yuk xati ID",
    ),
    "net_payments": (
        "Hamkor",
        "Biz",
        "Kim yozgan",
        "Holati",
        "Yozilgan",
        "Valyuta",
        "Summa",
        "Izoh",
        "Rad etish sababi",
        "Daftarimizda",
        "To'lov ID",
    ),
    "net_buyer": "Xaridor",
    "net_supplier": "Ta'minotchi",
    "net_own": "Biz",
    "net_partner": "Hamkor",
    "net_removed": "(o'chirilgan)",
    # What a counted item is counted in (`qarz.domain.stock.UNITS`): `GET .../stock/settings`, the bot's /ombor.
    "unit_dona": "dona",
    "unit_kg": "kg",
    "unit_g": "g",
    "unit_l": "litr",
    "unit_ml": "ml",
    "unit_m": "metr",
    "unit_quti": "quti",
    "unit_paket": "paket",
    "unit_juft": "juft",
    "unit_qop": "qop",
    "unit_blok": "blok",
    # The cash book's categories as they are named when they are made for a shop, in its language then
    # (`qarz.domain.cash.DEFAULT_CATEGORIES`, and the stock's own two). After that a name is the shop's data.
    "cash_category_sales": "Savdo",
    "cash_category_debt_repaid": "Qarz qaytdi",
    "cash_category_opening_balance": "Boshlang'ich qoldiq",
    "cash_category_other_income": "Boshqa kirim",
    "cash_category_purchase": "Tovar xaridi",
    "cash_category_rent": "Ijara",
    "cash_category_wages": "Ish haqi",
    "cash_category_transport": "Transport",
    "cash_category_utilities": "Kommunal to'lovlar",
    "cash_category_other_expense": "Boshqa chiqim",
    "cash_category_goods_purchase": "Ombor: tovar xaridi",
    "cash_category_customer_refund": "Ombor: mijozga qaytarildi",
    # The states of a partnership, an order, a delivery note and a payment in the network's sheets.
    "net_link_requested": "So'ralgan",
    "net_link_active": "Faol",
    "net_link_declined": "Rad etilgan",
    "net_link_ended": "Tugatilgan",
    "net_order_sent": "Yuborilgan",
    "net_order_accepted": "Qabul qilingan",
    "net_order_delivered": "Yetkazilgan",
    "net_order_received": "Olingan",
    "net_order_declined": "Rad etilgan",
    "net_order_cancelled": "Bekor qilingan",
    "net_note_issued": "Tasdiq kutilmoqda",
    "net_note_received": "Qabul qilingan",
    "net_note_rejected": "Rad etilgan",
    "net_note_superseded": "O'rniga yangisi yozilgan",
    "net_note_void": "Bekor",
    "net_payment_awaiting": "Javob kutilmoqda",
    "net_payment_confirmed": "Tasdiqlangan",
    "net_payment_declined": "Rad etilgan",
    "net_payment_withdrawn": "Qaytarib olingan",
    "net_payment_lapsed": "Muddati o'tgan",
}

RU: dict[str, str | tuple[str, ...]] = {
    "sheet_summary": "Отчёт",
    "sheet_customers": "Клиенты",
    "sheet_ledger": "Книга",
    "sheet_promises": "История сроков",
    "sheet_goods": "Товары",
    "sheet_cash": "Касса",
    "cash": (
        "День",
        "Время записи",
        "Направление",
        "Способ оплаты",
        "Валюта",
        "Сумма",
        "Статья",
        "Примечание",
        "Отменена",
        "Причина отмены",
        "Кто записал",
        "ID сотрудника",
        "Оплата в книге (ID)",
        "ID записи",
    ),
    "cash_income": "Приход",
    "cash_expense": "Расход",
    "cash_cash": "Наличные",
    "cash_card": "Карта",
    "cash_transfer": "Перевод",
    # An export of one period of the cash book (`qarz.application.cash_export`).
    "cash_period": (
        "День",
        "Время записи",
        "Направление",
        "Способ оплаты",
        "Валюта",
        "Сумма",
        "Статья",
        "Примечание",
        "Источник",
        "Отменена",
        "Причина отмены",
        "Время отмены",
        "ID сотрудника",
        "ID записи",
    ),
    "cash_customer": "Клиент",
    "cash_source_manual": "Записано вручную",
    "cash_source_ledger": "Оплата клиента",
    "cash_source_stock": "Склад",
    "cash_reversed": "Оплата клиента была отменена",
    "cash_period_from": "Начало периода",
    "cash_period_to": "Конец периода",
    "cash_entries_count": "Число записей (вместе с отменёнными)",
    "cash_balances_title": "Остатки",
    "cash_balances": (
        "Валюта",
        "Способ оплаты",
        "На начало периода",
        "Приход",
        "Расход",
        "На конец периода",
        "Записи",
    ),
    "cash_all_methods": "Итого",
    "cash_categories_title": "По статьям",
    "cash_categories": (
        "Валюта",
        "Направление",
        "Статья",
        "Сумма",
        "Записи",
    ),
    "cash_summary_note": (
        "Отменённые записи не учитываются. Сумы и доллары считаются отдельно: они никогда не складываются."
    ),
    "customers": ("Клиент", "Телефон", "Состояние", "Лимит долга", "Долг", "Дата добавления", "ID клиента"),
    "ledger": (
        "Дата и время",
        "Клиент",
        "Вид",
        "Сумма",
        "Влияние на долг",
        "Заметка",
        "Срок оплаты",
        "Отменена ли",
        "Какую запись отменяет (ID)",
        "Кто записал",
        "ID сотрудника",
        "Номер у клиента",
        "ID записи",
        "ID клиента",
    ),
    "promises": ("ID записи", "Клиент", "Срок оплаты", "Когда задан", "Кто задал", "Причина"),
    "goods": ("ID записи", "Дата и время", "Клиент", "Строка", "Товар", "Количество", "Единица", "Цена", "Итого"),
    "months": (
        "Месяц",
        "Сумма продаж в долг",
        "Число продаж в долг",
        "Сумма начальных долгов",
        "Сумма оплат",
        "Число оплат",
        "Число отменённых записей",
    ),
    "summary_shop": "Магазин",
    "summary_made": "Время выгрузки (Ташкент)",
    "summary_customers": "Число клиентов",
    "summary_debtors": "Число должников",
    "summary_outstanding": "Всего долг",
    "currency": "Валюта",
    "limit_usd": "Лимит долга ($)",
    "owed_usd": "Долг ($)",
    "summary_debtors_usd": "Число должников в долларах",
    "summary_outstanding_usd": "Всего долг ($)",
    "summary_advances": "Предоплаты клиентов (авансы)",
    "summary_advances_usd": "Предоплаты клиентов ($)",
    "summary_months_usd": "По месяцам, в долларах (отменённые записи и записи об отмене не учтены)",
    "summary_entries": "Число записей в книге",
    "summary_months": "По месяцам (отменённые записи и записи об отмене не учтены)",
    "kind_credit": "Продажа в долг",
    "kind_opening": "Начальный долг",
    "kind_payment": "Оплата",
    "kind_reversal": "Отмена",
    "status_active": "Активен",
    "status_archived": "В архиве",
    "status_anonymized": "Данные удалены",
    "role_seller": "Продавец",
    "role_manager": "Менеджер",
    "role_owner": "Владелец",
    "actor_default": "Срок магазина по умолчанию",
    "actor_staff": "Сотрудник",
    "actor_customer_request": "По просьбе клиента",
    "yes": "Да",
    "no": "Нет",
    "sheet_stock": "Склад",
    "sheet_stock_movements": "Движения склада",
    "sheet_stock_documents": "Документы склада",
    "sheet_suppliers": "Поставщики",
    "sheet_supplier_entries": "Расчёты с поставщиками",
    "stock": (
        "Товар",
        "Единица",
        "Цена продажи",
        "Остаток",
        "Порог малого остатка",
        "Валюта себестоимости",
        "Средняя себестоимость",
        "Стоимость остатка (по себестоимости)",
        "Штрихкоды",
        "ID товара",
    ),
    "stock_movements": (
        "Дата и время",
        "Товар",
        "Вид",
        "Количество",
        "Единица",
        "Остаток после движения",
        "Себестоимость (всего)",
        "Валюта",
        "Сумма продажи",
        "Причина",
        "Документ",
        "Отменено ли",
        "ID движения",
        "ID товара",
    ),
    "stock_documents": (
        "Номер",
        "Вид",
        "Состояние",
        "Дата",
        "Поставщик",
        "Клиент",
        "Валюта",
        "Итого",
        "Оплачено",
        "Причина",
        "Заметка",
        "Причина отмены",
        "ID документа",
    ),
    "suppliers": ("Поставщик", "Телефон", "Заметка", "Состояние", "Наш долг (сум)", "Наш долг ($)", "ID поставщика"),
    "supplier_entries": (
        "Дата и время",
        "Поставщик",
        "Вид",
        "Сумма",
        "Валюта",
        "Влияние на долг",
        "Заметка",
        "Отменена ли",
        "Документ",
        "ID записи",
        "ID поставщика",
    ),
    "movement_receipt": "Приход",
    "movement_sale": "Продажа",
    "movement_customer_return": "Возврат от клиента",
    "movement_supplier_return": "Возврат поставщику",
    "movement_write_off": "Списание",
    "movement_correction": "Поправка инвентаризации",
    "movement_reversal": "Отмена",
    "document_receipt": "Приход",
    "document_customer_return": "Возврат от клиента",
    "document_supplier_return": "Возврат поставщику",
    "document_write_off": "Списание",
    "document_stocktake": "Инвентаризация",
    "document_draft": "Черновик",
    "document_posted": "Проведён",
    "document_cancelled": "Отменён",
    "reason_damaged": "Повреждён",
    "reason_expired": "Истёк срок",
    "reason_lost": "Утерян",
    "reason_own_use": "Для себя",
    "supplier_purchase": "Получен товар",
    "supplier_opening": "Начальный долг",
    "supplier_payment": "Оплата",
    "supplier_return": "Возврат товара",
    "supplier_reversal": "Отмена",
    "sheet_net_links": "Партнёры",
    "sheet_net_orders": "Заказы партнёров",
    "sheet_net_notes": "Накладные",
    "sheet_net_payments": "Оплаты партнёров",
    "net_links": (
        "Партнёр",
        "Телефон",
        "Мы",
        "Состояние",
        "Запрошено",
        "Завершено",
        "ID связи",
    ),
    "net_orders": (
        "Партнёр",
        "Мы",
        "Заказ №",
        "Состояние",
        "Отправлен",
        "Нужная дата",
        "Заметка",
        "Валюта",
        "Итого",
        "Строка",
        "Товар",
        "Единица",
        "Запрошено",
        "Принято",
        "Цена",
        "Причина",
        "ID заказа",
    ),
    "net_notes": (
        "Партнёр",
        "Мы",
        "Накладная №",
        "Заказ №",
        "Состояние",
        "Оформлена",
        "Валюта",
        "Итого",
        "Оплачено",
        "Строка",
        "Товар",
        "Единица",
        "Количество",
        "Цена",
        "Сумма",
        "Причина отклонения",
        "Причина исправления",
        "ID накладной",
    ),
    "net_payments": (
        "Партнёр",
        "Мы",
        "Кто записал",
        "Состояние",
        "Записано",
        "Валюта",
        "Сумма",
        "Заметка",
        "Причина отклонения",
        "В нашем учёте",
        "ID оплаты",
    ),
    "net_buyer": "Покупатель",
    "net_supplier": "Поставщик",
    "net_own": "Мы",
    "net_partner": "Партнёр",
    "net_removed": "(удалён)",
    # What a counted item is counted in (`qarz.domain.stock.UNITS`): `GET .../stock/settings`, the bot's /ombor.
    "unit_dona": "шт",
    "unit_kg": "кг",
    "unit_g": "г",
    "unit_l": "л",
    "unit_ml": "мл",
    "unit_m": "м",
    "unit_quti": "коробка",
    "unit_paket": "пакет",
    "unit_juft": "пара",
    "unit_qop": "мешок",
    "unit_blok": "блок",
    # The cash book's categories as they are named when they are made for a shop, in its language then
    # (`qarz.domain.cash.DEFAULT_CATEGORIES`, and the stock's own two). After that a name is the shop's data.
    "cash_category_sales": "Продажи",
    "cash_category_debt_repaid": "Возврат долга",
    "cash_category_opening_balance": "Начальный остаток",
    "cash_category_other_income": "Прочий приход",
    "cash_category_purchase": "Закупка товара",
    "cash_category_rent": "Аренда",
    "cash_category_wages": "Зарплата",
    "cash_category_transport": "Транспорт",
    "cash_category_utilities": "Коммунальные услуги",
    "cash_category_other_expense": "Прочий расход",
    "cash_category_goods_purchase": "Склад: закупка товара",
    "cash_category_customer_refund": "Склад: возврат клиенту",
    # The states of a partnership, an order, a delivery note and a payment in the network's sheets.
    "net_link_requested": "Запрошена",
    "net_link_active": "Действует",
    "net_link_declined": "Отклонена",
    "net_link_ended": "Завершена",
    "net_order_sent": "Отправлен",
    "net_order_accepted": "Принят",
    "net_order_delivered": "Отгружен",
    "net_order_received": "Получен",
    "net_order_declined": "Отклонён",
    "net_order_cancelled": "Отменён",
    "net_note_issued": "Ждёт подтверждения",
    "net_note_received": "Принята",
    "net_note_rejected": "Отклонена",
    "net_note_superseded": "Заменена новой",
    "net_note_void": "Аннулирована",
    "net_payment_awaiting": "Ждёт ответа",
    "net_payment_confirmed": "Подтверждён",
    "net_payment_declined": "Отклонён",
    "net_payment_withdrawn": "Отозван",
    "net_payment_lapsed": "Истёк",
}

# Uzbek Cyrillic entries written by hand; the rest is the Uzbek entry transliterated (see `_entry`).
UZ_CYRILLIC: dict[str, str | tuple[str, ...]] = {}

# What each language has of its own. Uzbek and Russian are complete; the others may lack keys.
CATALOGS: Mapping[str, Mapping[str, str | tuple[str, ...]]] = {
    "uz": UZ,
    languages.UZ_CYRILLIC: UZ_CYRILLIC,
    "ru": RU,
    "tg": texts_tg.EXPORT,
    "kaa": texts_kaa.EXPORT,
    "en": texts_en.EXPORT,
}


@cache
def _entry(lang: str, key: str) -> str | tuple[str, ...] | None:
    """A language's own entry; without one the Uzbek entry, transliterated for Uzbek Cyrillic."""
    own = CATALOGS.get(lang, UZ).get(key)
    if own is not None:
        return own
    source = UZ.get(key)
    if source is None or lang != languages.UZ_CYRILLIC:
        return source
    return to_cyrillic(source) if isinstance(source, str) else tuple(to_cyrillic(title) for title in source)


def word(lang: str, key: str, fallback: str | None = None) -> str:
    """One word or phrase. A language without it reads Uzbek; an unknown key reads `fallback` when given."""
    value = _entry(lang, key)
    if value is None:
        value = fallback
    if not isinstance(value, str):
        raise KeyError(key)
    return value


def in_every_language(key: str) -> dict[str, str]:
    """One word in each of the six languages, by its tag: for an answer whose reader's language the server
    is not told (the names of units and write-off reasons, as the names of permissions)."""
    return {lang: word(lang, key) for lang in languages.LANGUAGES}


def header(lang: str, key: str) -> tuple[str, ...]:
    value = _entry(lang, key)
    if value is None or isinstance(value, str):
        raise KeyError(key)
    return value
