"""Words of the export workbook in Uzbek and Russian (ADR-021: interface text lives in catalogs).

Uzbek defines the keys; `tests/test_export_texts.py` requires Russian to mirror them, list for list.
"""

UZ: dict[str, str | tuple[str, ...]] = {
    "sheet_summary": "Hisobot",
    "sheet_customers": "Mijozlar",
    "sheet_ledger": "Daftar",
    "sheet_promises": "Muddatlar tarixi",
    "sheet_goods": "Mahsulotlar",
    "customers": ("Mijoz", "Telefon", "Holati", "Nasiya limiti", "Qarzi", "Qo'shilgan sana", "Mijoz ID"),
    "ledger": (
        "Sana va vaqt",
        "Mijoz",
        "Turi",
        "Summa",
        "Qarzga ta'siri",
        "Izoh",
        "To'lash muddati",
        "Bekor qilinganmi",
        "Bekor qilgan yozuvi (ID)",
        "Kim yozgan",
        "Xodim ID",
        "Mijozdagi tartib raqami",
        "Yozuv ID",
        "Mijoz ID",
    ),
    "promises": ("Yozuv ID", "Mijoz", "To'lash muddati", "Belgilangan vaqt", "Kim belgilagan", "Sabab"),
    "goods": ("Yozuv ID", "Sana va vaqt", "Mijoz", "Qator", "Mahsulot", "Miqdor", "Birlik", "Narxi", "Jami"),
    "months": (
        "Oy",
        "Nasiya summasi",
        "Nasiya soni",
        "Boshlang'ich qarz summasi",
        "To'lovlar summasi",
        "To'lovlar soni",
        "Bekor qilingan yozuvlar soni",
    ),
    "summary_shop": "Do'kon",
    "summary_made": "Eksport vaqti (Toshkent)",
    "summary_customers": "Mijozlar soni",
    "summary_debtors": "Qarzdor mijozlar soni",
    "summary_outstanding": "Jami qarz",
    # Only in the workbook of a shop that has dollar entries: its so'm figures stay where they were, and
    # the dollar ones are further columns and further rows, never part of a so'm total.
    "currency": "Valyuta",
    "limit_usd": "Nasiya limiti ($)",
    "owed_usd": "Qarzi ($)",
    "summary_debtors_usd": "Dollarda qarzdor mijozlar soni",
    "summary_outstanding_usd": "Jami qarz ($)",
    "summary_months_usd": (
        "Oylar bo'yicha, dollarda (bekor qilingan yozuvlar va bekor qilish yozuvlari hisobga olinmagan)"
    ),
    "summary_entries": "Daftardagi yozuvlar soni",
    "summary_months": "Oylar bo'yicha (bekor qilingan yozuvlar va bekor qilish yozuvlari hisobga olinmagan)",
    "kind_credit": "Nasiya",
    "kind_opening": "Boshlang'ich qarz",
    "kind_payment": "To'lov",
    "kind_reversal": "Bekor qilish",
    "status_active": "Faol",
    "status_archived": "Arxivda",
    "status_anonymized": "Ma'lumotlari o'chirilgan",
    "role_seller": "Sotuvchi",
    "role_manager": "Menejer",
    "role_owner": "Do'kon egasi",
    "actor_default": "Do'kon bo'yicha odatiy muddat",
    "actor_staff": "Xodim",
    "actor_customer_request": "Mijoz so'rovi bilan",
    "yes": "Ha",
    "no": "Yo'q",
    # The stock and the suppliers (expansion module I): only in the workbook of a shop that has any.
    "sheet_stock": "Ombor",
    "sheet_stock_movements": "Ombor harakatlari",
    "sheet_stock_documents": "Ombor hujjatlari",
    "sheet_suppliers": "Ta'minotchilar",
    "sheet_supplier_entries": "Ta'minotchi hisobi",
    "stock": (
        "Tovar",
        "Birlik",
        "Sotuv narxi",
        "Qoldiq",
        "Kam qoldiq chegarasi",
        "Tannarx valyutasi",
        "O'rtacha tannarx",
        "Qoldiq qiymati (tannarxda)",
        "Shtrix-kodlar",
        "Tovar ID",
    ),
    "stock_movements": (
        "Sana va vaqt",
        "Tovar",
        "Turi",
        "Miqdor",
        "Birlik",
        "Harakatdan keyingi qoldiq",
        "Tannarx (jami)",
        "Valyuta",
        "Sotuv summasi",
        "Sabab",
        "Hujjat",
        "Bekor qilinganmi",
        "Harakat ID",
        "Tovar ID",
    ),
    "stock_documents": (
        "Raqam",
        "Turi",
        "Holati",
        "Sana",
        "Ta'minotchi",
        "Mijoz",
        "Valyuta",
        "Jami",
        "To'langan",
        "Sabab",
        "Izoh",
        "Bekor qilish sababi",
        "Hujjat ID",
    ),
    "suppliers": ("Ta'minotchi", "Telefon", "Izoh", "Holati", "Qarzimiz (so'm)", "Qarzimiz ($)", "Ta'minotchi ID"),
    "supplier_entries": (
        "Sana va vaqt",
        "Ta'minotchi",
        "Turi",
        "Summa",
        "Valyuta",
        "Qarzga ta'siri",
        "Izoh",
        "Bekor qilinganmi",
        "Hujjat",
        "Yozuv ID",
        "Ta'minotchi ID",
    ),
    "movement_receipt": "Kirim",
    "movement_sale": "Sotuv",
    "movement_customer_return": "Mijozdan qaytdi",
    "movement_supplier_return": "Ta'minotchiga qaytarildi",
    "movement_write_off": "Hisobdan chiqarildi",
    "movement_correction": "Inventarizatsiya tuzatishi",
    "movement_reversal": "Bekor qilish",
    "document_receipt": "Kirim",
    "document_customer_return": "Mijozdan qaytarish",
    "document_supplier_return": "Ta'minotchiga qaytarish",
    "document_write_off": "Hisobdan chiqarish",
    "document_stocktake": "Inventarizatsiya",
    "document_draft": "Qoralama",
    "document_posted": "O'tkazilgan",
    "document_cancelled": "Bekor qilingan",
    "reason_damaged": "Shikastlangan",
    "reason_expired": "Muddati o'tgan",
    "reason_lost": "Yo'qolgan",
    "reason_own_use": "O'z ehtiyojiga",
    "supplier_purchase": "Tovar olindi",
    "supplier_opening": "Boshlang'ich qarz",
    "supplier_payment": "To'lov",
    "supplier_return": "Tovar qaytarildi",
    "supplier_reversal": "Bekor qilish",
}

RU: dict[str, str | tuple[str, ...]] = {
    "sheet_summary": "Отчёт",
    "sheet_customers": "Клиенты",
    "sheet_ledger": "Книга",
    "sheet_promises": "История сроков",
    "sheet_goods": "Товары",
    "customers": ("Клиент", "Телефон", "Состояние", "Лимит долга", "Долг", "Дата добавления", "ID клиента"),
    "ledger": (
        "Дата и время",
        "Клиент",
        "Вид",
        "Сумма",
        "Влияние на долг",
        "Заметка",
        "Срок оплаты",
        "Отменена ли",
        "Какую запись отменяет (ID)",
        "Кто записал",
        "ID сотрудника",
        "Номер у клиента",
        "ID записи",
        "ID клиента",
    ),
    "promises": ("ID записи", "Клиент", "Срок оплаты", "Когда задан", "Кто задал", "Причина"),
    "goods": ("ID записи", "Дата и время", "Клиент", "Строка", "Товар", "Количество", "Единица", "Цена", "Итого"),
    "months": (
        "Месяц",
        "Сумма продаж в долг",
        "Число продаж в долг",
        "Сумма начальных долгов",
        "Сумма оплат",
        "Число оплат",
        "Число отменённых записей",
    ),
    "summary_shop": "Магазин",
    "summary_made": "Время выгрузки (Ташкент)",
    "summary_customers": "Число клиентов",
    "summary_debtors": "Число должников",
    "summary_outstanding": "Всего долг",
    "currency": "Валюта",
    "limit_usd": "Лимит долга ($)",
    "owed_usd": "Долг ($)",
    "summary_debtors_usd": "Число должников в долларах",
    "summary_outstanding_usd": "Всего долг ($)",
    "summary_months_usd": "По месяцам, в долларах (отменённые записи и записи об отмене не учтены)",
    "summary_entries": "Число записей в книге",
    "summary_months": "По месяцам (отменённые записи и записи об отмене не учтены)",
    "kind_credit": "Продажа в долг",
    "kind_opening": "Начальный долг",
    "kind_payment": "Оплата",
    "kind_reversal": "Отмена",
    "status_active": "Активен",
    "status_archived": "В архиве",
    "status_anonymized": "Данные удалены",
    "role_seller": "Продавец",
    "role_manager": "Менеджер",
    "role_owner": "Владелец",
    "actor_default": "Срок магазина по умолчанию",
    "actor_staff": "Сотрудник",
    "actor_customer_request": "По просьбе клиента",
    "yes": "Да",
    "no": "Нет",
    "sheet_stock": "Склад",
    "sheet_stock_movements": "Движения склада",
    "sheet_stock_documents": "Документы склада",
    "sheet_suppliers": "Поставщики",
    "sheet_supplier_entries": "Расчёты с поставщиками",
    "stock": (
        "Товар",
        "Единица",
        "Цена продажи",
        "Остаток",
        "Порог малого остатка",
        "Валюта себестоимости",
        "Средняя себестоимость",
        "Стоимость остатка (по себестоимости)",
        "Штрихкоды",
        "ID товара",
    ),
    "stock_movements": (
        "Дата и время",
        "Товар",
        "Вид",
        "Количество",
        "Единица",
        "Остаток после движения",
        "Себестоимость (всего)",
        "Валюта",
        "Сумма продажи",
        "Причина",
        "Документ",
        "Отменено ли",
        "ID движения",
        "ID товара",
    ),
    "stock_documents": (
        "Номер",
        "Вид",
        "Состояние",
        "Дата",
        "Поставщик",
        "Клиент",
        "Валюта",
        "Итого",
        "Оплачено",
        "Причина",
        "Заметка",
        "Причина отмены",
        "ID документа",
    ),
    "suppliers": ("Поставщик", "Телефон", "Заметка", "Состояние", "Наш долг (сум)", "Наш долг ($)", "ID поставщика"),
    "supplier_entries": (
        "Дата и время",
        "Поставщик",
        "Вид",
        "Сумма",
        "Валюта",
        "Влияние на долг",
        "Заметка",
        "Отменена ли",
        "Документ",
        "ID записи",
        "ID поставщика",
    ),
    "movement_receipt": "Приход",
    "movement_sale": "Продажа",
    "movement_customer_return": "Возврат от клиента",
    "movement_supplier_return": "Возврат поставщику",
    "movement_write_off": "Списание",
    "movement_correction": "Поправка инвентаризации",
    "movement_reversal": "Отмена",
    "document_receipt": "Приход",
    "document_customer_return": "Возврат от клиента",
    "document_supplier_return": "Возврат поставщику",
    "document_write_off": "Списание",
    "document_stocktake": "Инвентаризация",
    "document_draft": "Черновик",
    "document_posted": "Проведён",
    "document_cancelled": "Отменён",
    "reason_damaged": "Повреждён",
    "reason_expired": "Истёк срок",
    "reason_lost": "Утерян",
    "reason_own_use": "Для себя",
    "supplier_purchase": "Получен товар",
    "supplier_opening": "Начальный долг",
    "supplier_payment": "Оплата",
    "supplier_return": "Возврат товара",
    "supplier_reversal": "Отмена",
}

CATALOGS = {"uz": UZ, "ru": RU}


def word(lang: str, key: str, fallback: str | None = None) -> str:
    """One word or phrase. An unknown language reads Uzbek; an unknown key reads `fallback` when given."""
    value = CATALOGS.get(lang, UZ).get(key, fallback)
    if not isinstance(value, str):
        raise KeyError(key)
    return value


def header(lang: str, key: str) -> tuple[str, ...]:
    value = CATALOGS.get(lang, UZ)[key]
    if isinstance(value, str):
        raise KeyError(key)
    return value
