import type { MessageKey } from "./messages";

/** English text of the page behind a customer's read-only link. A key that is absent here reads Uzbek. */
export const en: Partial<Record<MessageKey, string>> = {
  "page.title": "My debt",
  "lang.uz": "O'zbekcha",
  "lang.ru": "Русский",
  "lang.uz-Cyrl": "Ўзбекча",
  "lang.tg": "Тоҷикӣ",
  "lang.kaa": "Qaraqalpaqsha",
  "lang.en": "English",
  "lang.choose": "Language",
  "state.loading": "Loading…",
  "gone.title": "The link does not work",
  "gone.body": "The link has expired, was revoked or was copied wrongly. Ask the shop for a new link.",
  "limited.title": "Too many tries",
  "limited.body": "Open the page again in a minute.",
  "offline.title": "Could not connect",
  "offline.body": "Check your internet and try again.",
  "action.retry": "Try again",
  "greeting": "{name}, this is your account",
  "greeting.noName": "This is your account",
  "shop.phone": "Shop phone: ",
  "balance.owed": "Your debt",
  "balance.none": "You have no debt",
  "balance.credit": "You are in credit by",
  "overdue": "Of which overdue: {amount}",
  "dueToday": "Due today: {amount}",
  "entries.title": "Entries",
  "entries.empty": "No entries yet.",
  "entries.shown": "Showing the latest {shown} of {total} entries.",
  "kind.credit": "Credit sale",
  "kind.opening": "Opening debt",
  "kind.payment": "Payment",
  "kind.reversal": "Reversal entry",
  "kind.other": "Entry",
  "entry.promised": "Due date: {date}",
  "entry.reversed": "Reversed",
  "line": "{name} — {qty} {unit} × {price} = {total}",
  "money": "{amount} soum",
  "date": "{day} {month} {year}",
  "foot.readOnly": "This page is read-only. If you see a mistake, contact the shop.",
  "foot.expires": "The link is valid until {date}.",
  "foot.secret": "This link is for you only: do not send it to others.",
  "month.1": "January",
  "month.2": "February",
  "month.3": "March",
  "month.4": "April",
  "month.5": "May",
  "month.6": "June",
  "month.7": "July",
  "month.8": "August",
  "month.9": "September",
  "month.10": "October",
  "month.11": "November",
  "month.12": "December",
};
