import type { MessageKey } from "./messages";

export const kaa: Partial<Record<MessageKey, string>> = {
  "page.title": "Meniń qarızım",
  "lang.uz": "O'zbekcha",
  "lang.ru": "Русский",
  "lang.uz-Cyrl": "Ўзбекча",
  "lang.tg": "Тоҷикӣ",
  "lang.kaa": "Qaraqalpaqsha",
  "lang.en": "English",
  "lang.choose": "Til",
  "state.loading": "Júklenbekte…",
  "gone.title": "Silteme islemey tur",
  "gone.body":
    "Siltemeniń múddeti tamamlanǵan, ol biykarlanǵan yamasa nadurıs kóshirilgen. Dúkannan jańa silteme sorań.",
  "limited.title": "Júdá kóp urınıw",
  "limited.body": "Bir minuttan keyin betti qayta ashıń.",
  "offline.title": "Jalǵanıp bolmadı",
  "offline.body": "Internetti tekserip, qayta urınıp kóriń.",
  "action.retry": "Qayta urınıw",
  "greeting": "{name}, bul sizdiń esabıńız",
  "greeting.noName": "Bul sizdiń esabıńız",
  "shop.phone": "Dúkan telefonı: ",
  "balance.owed": "Qarızıńız",
  "balance.none": "Qarızıńız joq",
  "balance.credit": "Artıq tólemińiz",
  "overdue": "Sonnan múddeti ótkeni: {amount}",
  "dueToday": "Búgin tóleniwi kerek: {amount}",
  "entries.title": "Jazbalar",
  "entries.empty": "Házirshe jazba joq.",
  "entries.shown": "Sońǵı {shown} jazba kórsetilgen, jámi {total}.",
  "kind.credit": "Nesiye",
  "kind.opening": "Baslanǵısh qarız",
  "kind.payment": "Tólem",
  "kind.reversal": "Biykarlaw jazbası",
  "kind.other": "Jazba",
  "entry.promised": "Tólew múddeti: {date}",
  "entry.reversed": "Biykarlanǵan",
  "line": "{name} — {qty} {unit} × {price} = {total}",
  "money": "{amount} swm",
  "date": "{year}-jıl {day}-{month}",
  "foot.readOnly": "Bul bet tek oqıw ushın. Qáte kórseńiz, dúkanǵa múrájat etiń.",
  "foot.expires": "Silteme {date} kúnine shekem isleydi.",
  "foot.secret": "Bul silteme tek siz ushın: onı basqalarǵa jibermeń.",
  "month.1": "yanvar",
  "month.2": "fevral",
  "month.3": "mart",
  "month.4": "aprel",
  "month.5": "may",
  "month.6": "iyun",
  "month.7": "iyul",
  "month.8": "avgust",
  "month.9": "sentyabr",
  "month.10": "oktyabr",
  "month.11": "noyabr",
  "month.12": "dekabr",
};
