import type { MessageKey } from "./messages";

/** Tajik text of the page behind a customer's read-only link. A key that is absent here reads Uzbek. */
export const tg: Partial<Record<MessageKey, string>> = {
  "page.title": "Қарзи ман",
  "lang.uz": "O'zbekcha",
  "lang.ru": "Русский",
  "lang.uz-Cyrl": "Ўзбекча",
  "lang.tg": "Тоҷикӣ",
  "lang.kaa": "Qaraqalpaqsha",
  "lang.en": "English",
  "lang.choose": "Забон",
  "state.loading": "Бор шуда истодааст…",
  "gone.title": "Пайванд кор намекунад",
  "gone.body":
    "Мӯҳлати пайванд тамом шудааст, он бекор шудааст ё нодуруст нусха гирифта шудааст. Аз мағоза пайванди нав пурсед.",
  "limited.title": "Кӯшишҳо хеле зиёданд",
  "limited.body": "Пас аз як дақиқа саҳифаро аз нав кушоед.",
  "offline.title": "Пайваст шуда нашуд",
  "offline.body": "Интернетро санҷед ва аз нав кӯшиш кунед.",
  "action.retry": "Аз нав кӯшидан",
  "greeting": "{name}, ин ҳисоби Шумост",
  "greeting.noName": "Ин ҳисоби Шумост",
  "shop.phone": "Телефони мағоза: ",
  "balance.owed": "Қарзи Шумо",
  "balance.none": "Шумо қарз надоред",
  "balance.credit": "Пардохти зиёдатии Шумо",
  "overdue": "Аз он мӯҳлаташ гузашта: {amount}",
  "dueToday": "Имрӯз бояд пардохт шавад: {amount}",
  "entries.title": "Сабтҳо",
  "entries.empty": "Ҳоло сабт нест.",
  "entries.shown": "{shown} сабти охирин нишон дода шудааст, ҳамагӣ {total} то.",
  "kind.credit": "Насия",
  "kind.opening": "Қарзи аввала",
  "kind.payment": "Пардохт",
  "kind.reversal": "Сабти бекоркунӣ",
  "kind.other": "Сабт",
  "entry.promised": "Мӯҳлати пардохт: {date}",
  "entry.reversed": "Бекор шудааст",
  "line": "{name} — {qty} {unit} × {price} = {total}",
  "money": "{amount} сӯм",
  "date": "{day} {month}и {year}",
  "foot.readOnly": "Ин саҳифа танҳо барои хондан аст. Агар хато бинед, ба мағоза муроҷиат кунед.",
  "foot.expires": "Пайванд то {date} амал мекунад.",
  "foot.secret": "Ин пайванд танҳо барои Шумост: онро ба дигарон нафиристед.",
  "month.1": "январ",
  "month.2": "феврал",
  "month.3": "март",
  "month.4": "апрел",
  "month.5": "май",
  "month.6": "июн",
  "month.7": "июл",
  "month.8": "август",
  "month.9": "сентябр",
  "month.10": "октябр",
  "month.11": "ноябр",
  "month.12": "декабр",
};
