/**
 * Uzbek (Latin) text of the page behind a customer's read-only link: the source of the page's other
 * languages. It defines the keys (`MessageKey` in `messages.ts`). This file imports nothing, so that the
 * scripts that write and check the other languages can read it without a bundler.
 */
export const uz = {
  "page.title": "Mening qarzim",
  "lang.uz": "O'zbekcha",
  "lang.ru": "Русский",
  "lang.uz-Cyrl": "Ўзбекча",
  "lang.tg": "Тоҷикӣ",
  "lang.kaa": "Qaraqalpaqsha",
  "lang.en": "English",
  "lang.choose": "Til",
  "state.loading": "Yuklanmoqda…",
  "gone.title": "Havola ishlamayapti",
  "gone.body":
    "Havolaning muddati tugagan, u bekor qilingan yoki noto'g'ri ko'chirilgan. Do'kondan yangi havola so'rang.",
  "limited.title": "Juda ko'p urinish",
  "limited.body": "Bir daqiqadan so'ng sahifani qayta oching.",
  "offline.title": "Ulanib bo'lmadi",
  "offline.body": "Internetni tekshirib, qayta urinib ko'ring.",
  "action.retry": "Qayta urinish",
  "greeting": "{name}, bu sizning hisobingiz",
  "greeting.noName": "Bu sizning hisobingiz",
  "shop.phone": "Do'kon telefoni: ",
  "balance.owed": "Qarzingiz",
  "balance.none": "Qarzingiz yo'q",
  "balance.credit": "Ortiqcha to'lovingiz",
  "overdue": "Shundan muddati o'tgani: {amount}",
  "dueToday": "Bugun to'lanishi kerak: {amount}",
  "entries.title": "Yozuvlar",
  "entries.empty": "Hozircha yozuv yo'q.",
  "entries.shown": "Oxirgi {shown} ta yozuv ko'rsatilgan, jami {total} ta.",
  "kind.credit": "Nasiya",
  "kind.opening": "Boshlang'ich qarz",
  "kind.payment": "To'lov",
  "kind.reversal": "Bekor qilish yozuvi",
  "kind.other": "Yozuv",
  "entry.promised": "To'lash muddati: {date}",
  "entry.reversed": "Bekor qilingan",
  "line": "{name} — {qty} {unit} × {price} = {total}",
  "money": "{amount} so'm",
  "date": "{year}-yil {day}-{month}",
  "foot.readOnly": "Bu sahifa faqat o'qish uchun. Xato ko'rsangiz, do'konga murojaat qiling.",
  "foot.expires": "Havola {date} gacha amal qiladi.",
  "foot.secret": "Bu havola faqat siz uchun: uni boshqalarga yubormang.",
  "month.1": "yanvar",
  "month.2": "fevral",
  "month.3": "mart",
  "month.4": "aprel",
  "month.5": "may",
  "month.6": "iyun",
  "month.7": "iyul",
  "month.8": "avgust",
  "month.9": "sentabr",
  "month.10": "oktabr",
  "month.11": "noyabr",
  "month.12": "dekabr",
} as const;
